// Code generated by MockGen. DO NOT EDIT.
// Source: ./interface.go
//
// Generated by this command:
//
//	mockgen -source=./interface.go -destination ./hlartracemock/artrace_mock.go -package hlartracemock
//

// Package hlartracemock is a generated GoMock package.
package hlartracemock

import (
	context "context"
	reflect "reflect"

	gin "github.com/gin-gonic/gin"
	trace "go.opentelemetry.io/otel/trace"
	gomock "go.uber.org/mock/gomock"
)

// MockTracer is a mock of Tracer interface.
type MockTracer struct {
	ctrl     *gomock.Controller
	recorder *MockTracerMockRecorder
	isgomock struct{}
}

// MockTracerMockRecorder is the mock recorder for MockTracer.
type MockTracerMockRecorder struct {
	mock *MockTracer
}

// NewMockTracer creates a new mock instance.
func NewMockTracer(ctrl *gomock.Controller) *MockTracer {
	mock := &MockTracer{ctrl: ctrl}
	mock.recorder = &MockTracerMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockTracer) EXPECT() *MockTracerMockRecorder {
	return m.recorder
}

// AddClientTrace mocks base method.
func (m *MockTracer) AddClientTrace(ctx context.Context) (context.Context, trace.Span) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "AddClientTrace", ctx)
	ret0, _ := ret[0].(context.Context)
	ret1, _ := ret[1].(trace.Span)
	return ret0, ret1
}

// AddClientTrace indicates an expected call of AddClientTrace.
func (mr *MockTracerMockRecorder) AddClientTrace(ctx any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "AddClientTrace", reflect.TypeOf((*MockTracer)(nil).AddClientTrace), ctx)
}

// AddConsumerTrace mocks base method.
func (m *MockTracer) AddConsumerTrace(ctx context.Context, topic string) (context.Context, trace.Span) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "AddConsumerTrace", ctx, topic)
	ret0, _ := ret[0].(context.Context)
	ret1, _ := ret[1].(trace.Span)
	return ret0, ret1
}

// AddConsumerTrace indicates an expected call of AddConsumerTrace.
func (mr *MockTracerMockRecorder) AddConsumerTrace(ctx, topic any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "AddConsumerTrace", reflect.TypeOf((*MockTracer)(nil).AddConsumerTrace), ctx, topic)
}

// AddInternalTrace mocks base method.
func (m *MockTracer) AddInternalTrace(ctx context.Context) (context.Context, trace.Span) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "AddInternalTrace", ctx)
	ret0, _ := ret[0].(context.Context)
	ret1, _ := ret[1].(trace.Span)
	return ret0, ret1
}

// AddInternalTrace indicates an expected call of AddInternalTrace.
func (mr *MockTracerMockRecorder) AddInternalTrace(ctx any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "AddInternalTrace", reflect.TypeOf((*MockTracer)(nil).AddInternalTrace), ctx)
}

// AddProducerTrace mocks base method.
func (m *MockTracer) AddProducerTrace(ctx context.Context) (context.Context, trace.Span) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "AddProducerTrace", ctx)
	ret0, _ := ret[0].(context.Context)
	ret1, _ := ret[1].(trace.Span)
	return ret0, ret1
}

// AddProducerTrace indicates an expected call of AddProducerTrace.
func (mr *MockTracerMockRecorder) AddProducerTrace(ctx any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "AddProducerTrace", reflect.TypeOf((*MockTracer)(nil).AddProducerTrace), ctx)
}

// AddServerTrace mocks base method.
func (m *MockTracer) AddServerTrace(c *gin.Context) (context.Context, trace.Span) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "AddServerTrace", c)
	ret0, _ := ret[0].(context.Context)
	ret1, _ := ret[1].(trace.Span)
	return ret0, ret1
}

// AddServerTrace indicates an expected call of AddServerTrace.
func (mr *MockTracerMockRecorder) AddServerTrace(c any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "AddServerTrace", reflect.TypeOf((*MockTracer)(nil).AddServerTrace), c)
}

// SetClientSpanName mocks base method.
func (m *MockTracer) SetClientSpanName(spanName string) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "SetClientSpanName", spanName)
}

// SetClientSpanName indicates an expected call of SetClientSpanName.
func (mr *MockTracerMockRecorder) SetClientSpanName(spanName any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SetClientSpanName", reflect.TypeOf((*MockTracer)(nil).SetClientSpanName), spanName)
}

// SetInternalSpanName mocks base method.
func (m *MockTracer) SetInternalSpanName(spanName string) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "SetInternalSpanName", spanName)
}

// SetInternalSpanName indicates an expected call of SetInternalSpanName.
func (mr *MockTracerMockRecorder) SetInternalSpanName(spanName any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SetInternalSpanName", reflect.TypeOf((*MockTracer)(nil).SetInternalSpanName), spanName)
}

// TelemetrySpanEnd mocks base method.
func (m *MockTracer) TelemetrySpanEnd(span trace.Span, err error) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "TelemetrySpanEnd", span, err)
}

// TelemetrySpanEnd indicates an expected call of TelemetrySpanEnd.
func (mr *MockTracerMockRecorder) TelemetrySpanEnd(span, err any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "TelemetrySpanEnd", reflect.TypeOf((*MockTracer)(nil).TelemetrySpanEnd), span, err)
}

// TelemetrySpanEndIgnoreDBNotFound mocks base method.
func (m *MockTracer) TelemetrySpanEndIgnoreDBNotFound(span trace.Span, err error) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "TelemetrySpanEndIgnoreDBNotFound", span, err)
}

// TelemetrySpanEndIgnoreDBNotFound indicates an expected call of TelemetrySpanEndIgnoreDBNotFound.
func (mr *MockTracerMockRecorder) TelemetrySpanEndIgnoreDBNotFound(span, err any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "TelemetrySpanEndIgnoreDBNotFound", reflect.TypeOf((*MockTracer)(nil).TelemetrySpanEndIgnoreDBNotFound), span, err)
}
