// Code generated by MockGen. DO NOT EDIT.
// Source: ./decision/policy_decision.go

// Package mock_descision is a generated GoMock package.
package mock_descision

import (
	context "context"
	reflect "reflect"

	models "policy_mgnt/utils/models"

	gomock "go.uber.org/mock/gomock"
)

// MockPolicyDecision is a mock of PolicyDecision interface.
type MockPolicyDecision struct {
	ctrl     *gomock.Controller
	recorder *MockPolicyDecisionMockRecorder
}

// MockPolicyDecisionMockRecorder is the mock recorder for MockPolicyDecision.
type MockPolicyDecisionMockRecorder struct {
	mock *MockPolicyDecision
}

// NewMockPolicyDecision creates a new mock instance.
func NewMockPolicyDecision(ctrl *gomock.Controller) *MockPolicyDecision {
	mock := &MockPolicyDecision{ctrl: ctrl}
	mock.recorder = &MockPolicyDecisionMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockPolicyDecision) EXPECT() *MockPolicyDecisionMockRecorder {
	return m.recorder
}

// ClientSignDecision mocks base method.
func (m *MockPolicyDecision) ClientSignDecision(ctx context.Context, clientType string) (bool, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ClientSignDecision", ctx, clientType)
	ret0, _ := ret[0].(bool)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ClientSignDecision indicates an expected call of ClientSignDecision.
func (mr *MockPolicyDecisionMockRecorder) ClientSignDecision(ctx, clientType interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ClientSignDecision", reflect.TypeOf((*MockPolicyDecision)(nil).ClientSignDecision), ctx, clientType)
}

// IncrementalUpdatePolicy mocks base method.
func (m *MockPolicyDecision) IncrementalUpdatePolicy(ctx context.Context, userId string, departmentPaths []string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "IncrementalUpdatePolicy", ctx, userId, departmentPaths)
	ret0, _ := ret[0].(error)
	return ret0
}

// IncrementalUpdatePolicy indicates an expected call of IncrementalUpdatePolicy.
func (mr *MockPolicyDecisionMockRecorder) IncrementalUpdatePolicy(ctx, userId, departmentPaths interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "IncrementalUpdatePolicy", reflect.TypeOf((*MockPolicyDecision)(nil).IncrementalUpdatePolicy), ctx, userId, departmentPaths)
}

// InitOpaData mocks base method.
func (m *MockPolicyDecision) InitOpaData() error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "InitOpaData")
	ret0, _ := ret[0].(error)
	return ret0
}

// InitOpaData indicates an expected call of InitOpaData.
func (mr *MockPolicyDecisionMockRecorder) InitOpaData() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "InitOpaData", reflect.TypeOf((*MockPolicyDecision)(nil).InitOpaData))
}

// NetWorkDecision mocks base method.
func (m *MockPolicyDecision) NetWorkDecision(ctx context.Context, reqBody models.Accessor) (bool, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "NetWorkDecision", ctx, reqBody)
	ret0, _ := ret[0].(bool)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// NetWorkDecision indicates an expected call of NetWorkDecision.
func (mr *MockPolicyDecisionMockRecorder) NetWorkDecision(ctx, reqBody interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "NetWorkDecision", reflect.TypeOf((*MockPolicyDecision)(nil).NetWorkDecision), ctx, reqBody)
}

// PublishChange mocks base method.
func (m *MockPolicyDecision) PublishChange(userId string, departmentPaths []string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "PublishChange", userId, departmentPaths)
	ret0, _ := ret[0].(error)
	return ret0
}

// PublishChange indicates an expected call of PublishChange.
func (mr *MockPolicyDecisionMockRecorder) PublishChange(userId, departmentPaths interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "PublishChange", reflect.TypeOf((*MockPolicyDecision)(nil).PublishChange), userId, departmentPaths)
}

// PublishInit mocks base method.
func (m *MockPolicyDecision) PublishInit() error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "PublishInit")
	ret0, _ := ret[0].(error)
	return ret0
}

// PublishInit indicates an expected call of PublishInit.
func (mr *MockPolicyDecisionMockRecorder) PublishInit() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "PublishInit", reflect.TypeOf((*MockPolicyDecision)(nil).PublishInit))
}

// ReadOPAData mocks base method.
func (m *MockPolicyDecision) ReadOPAData(ctx context.Context, path string) (interface{}, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ReadOPAData", ctx, path)
	ret0, _ := ret[0].(interface{})
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ReadOPAData indicates an expected call of ReadOPAData.
func (mr *MockPolicyDecisionMockRecorder) ReadOPAData(ctx, path interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ReadOPAData", reflect.TypeOf((*MockPolicyDecision)(nil).ReadOPAData), ctx, path)
}
