// Code generated by MockGen. DO NOT EDIT.
// Source: ./sharemgnt.go
//
// Generated by this command:
//
//	mockgen -package mock_thrift -source ./sharemgnt.go -destination ../test/mock_thrift/sharemgnt_mock.go
//

// Package mock_thrift is a generated GoMock package.
package mock_thrift

import (
	sharemgnt "policy_mgnt/tapi/sharemgnt"
	reflect "reflect"

	gomock "go.uber.org/mock/gomock"
)

// MockShareMgnt is a mock of ShareMgnt interface.
type MockShareMgnt struct {
	ctrl     *gomock.Controller
	recorder *MockShareMgntMockRecorder
	isgomock struct{}
}

// MockShareMgntMockRecorder is the mock recorder for MockShareMgnt.
type MockShareMgntMockRecorder struct {
	mock *MockShareMgnt
}

// NewMockShareMgnt creates a new mock instance.
func NewMockShareMgnt(ctrl *gomock.Controller) *MockShareMgnt {
	mock := &MockShareMgnt{ctrl: ctrl}
	mock.recorder = &MockShareMgntMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockShareMgnt) EXPECT() *MockShareMgntMockRecorder {
	return m.recorder
}

// ApplyImageVcode mocks base method.
func (m *MockShareMgnt) ApplyImageVcode(arg0 sharemgnt.NcTVcodeConfig) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ApplyImageVcode", arg0)
	ret0, _ := ret[0].(error)
	return ret0
}

// ApplyImageVcode indicates an expected call of ApplyImageVcode.
func (mr *MockShareMgntMockRecorder) ApplyImageVcode(arg0 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ApplyImageVcode", reflect.TypeOf((*MockShareMgnt)(nil).ApplyImageVcode), arg0)
}

// ApplyMultiFactorAuth mocks base method.
func (m *MockShareMgnt) ApplyMultiFactorAuth(arg0, arg1 string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ApplyMultiFactorAuth", arg0, arg1)
	ret0, _ := ret[0].(error)
	return ret0
}

// ApplyMultiFactorAuth indicates an expected call of ApplyMultiFactorAuth.
func (mr *MockShareMgntMockRecorder) ApplyMultiFactorAuth(arg0, arg1 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ApplyMultiFactorAuth", reflect.TypeOf((*MockShareMgnt)(nil).ApplyMultiFactorAuth), arg0, arg1)
}

// ApplyPasswordStrengthMeter mocks base method.
func (m *MockShareMgnt) ApplyPasswordStrengthMeter(arg0 sharemgnt.NcTUsrmPasswordConfig) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ApplyPasswordStrengthMeter", arg0)
	ret0, _ := ret[0].(error)
	return ret0
}

// ApplyPasswordStrengthMeter indicates an expected call of ApplyPasswordStrengthMeter.
func (mr *MockShareMgntMockRecorder) ApplyPasswordStrengthMeter(arg0 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ApplyPasswordStrengthMeter", reflect.TypeOf((*MockShareMgnt)(nil).ApplyPasswordStrengthMeter), arg0)
}

// GetAllOrgs mocks base method.
func (m *MockShareMgnt) GetAllOrgs() ([]*sharemgnt.NcTRootOrgInfo, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetAllOrgs")
	ret0, _ := ret[0].([]*sharemgnt.NcTRootOrgInfo)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetAllOrgs indicates an expected call of GetAllOrgs.
func (mr *MockShareMgntMockRecorder) GetAllOrgs() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetAllOrgs", reflect.TypeOf((*MockShareMgnt)(nil).GetAllOrgs))
}

// GetDepartmentByID mocks base method.
func (m *MockShareMgnt) GetDepartmentByID(arg0 string) (*sharemgnt.NcTUsrmDepartmentInfo, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetDepartmentByID", arg0)
	ret0, _ := ret[0].(*sharemgnt.NcTUsrmDepartmentInfo)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetDepartmentByID indicates an expected call of GetDepartmentByID.
func (mr *MockShareMgntMockRecorder) GetDepartmentByID(arg0 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetDepartmentByID", reflect.TypeOf((*MockShareMgnt)(nil).GetDepartmentByID), arg0)
}

// GetHostName mocks base method.
func (m *MockShareMgnt) GetHostName() (string, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetHostName")
	ret0, _ := ret[0].(string)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetHostName indicates an expected call of GetHostName.
func (mr *MockShareMgntMockRecorder) GetHostName() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetHostName", reflect.TypeOf((*MockShareMgnt)(nil).GetHostName))
}

// GetOrganizationByID mocks base method.
func (m *MockShareMgnt) GetOrganizationByID(arg0 string) (*sharemgnt.NcTUsrmOrganizationInfo, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetOrganizationByID", arg0)
	ret0, _ := ret[0].(*sharemgnt.NcTUsrmOrganizationInfo)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetOrganizationByID indicates an expected call of GetOrganizationByID.
func (mr *MockShareMgntMockRecorder) GetOrganizationByID(arg0 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetOrganizationByID", reflect.TypeOf((*MockShareMgnt)(nil).GetOrganizationByID), arg0)
}

// GetPasswordConfig mocks base method.
func (m *MockShareMgnt) GetPasswordConfig() (*sharemgnt.NcTUsrmPasswordConfig, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetPasswordConfig")
	ret0, _ := ret[0].(*sharemgnt.NcTUsrmPasswordConfig)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetPasswordConfig indicates an expected call of GetPasswordConfig.
func (mr *MockShareMgntMockRecorder) GetPasswordConfig() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetPasswordConfig", reflect.TypeOf((*MockShareMgnt)(nil).GetPasswordConfig))
}

// GetUserByID mocks base method.
func (m *MockShareMgnt) GetUserByID(arg0 string) (*sharemgnt.NcTUsrmGetUserInfo, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetUserByID", arg0)
	ret0, _ := ret[0].(*sharemgnt.NcTUsrmGetUserInfo)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetUserByID indicates an expected call of GetUserByID.
func (mr *MockShareMgntMockRecorder) GetUserByID(arg0 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetUserByID", reflect.TypeOf((*MockShareMgnt)(nil).GetUserByID), arg0)
}

// SearchDepartments mocks base method.
func (m *MockShareMgnt) SearchDepartments(arg0, arg1 string, arg2, arg3 int) ([]*sharemgnt.NcTUsrmDepartmentInfo, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SearchDepartments", arg0, arg1, arg2, arg3)
	ret0, _ := ret[0].([]*sharemgnt.NcTUsrmDepartmentInfo)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// SearchDepartments indicates an expected call of SearchDepartments.
func (mr *MockShareMgntMockRecorder) SearchDepartments(arg0, arg1, arg2, arg3 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SearchDepartments", reflect.TypeOf((*MockShareMgnt)(nil).SearchDepartments), arg0, arg1, arg2, arg3)
}

// SearchSupervisoryUsers mocks base method.
func (m *MockShareMgnt) SearchSupervisoryUsers(arg0, arg1 string, arg2, arg3 int) ([]*sharemgnt.NcTSearchUserInfo, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SearchSupervisoryUsers", arg0, arg1, arg2, arg3)
	ret0, _ := ret[0].([]*sharemgnt.NcTSearchUserInfo)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// SearchSupervisoryUsers indicates an expected call of SearchSupervisoryUsers.
func (mr *MockShareMgntMockRecorder) SearchSupervisoryUsers(arg0, arg1, arg2, arg3 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SearchSupervisoryUsers", reflect.TypeOf((*MockShareMgnt)(nil).SearchSupervisoryUsers), arg0, arg1, arg2, arg3)
}
