import { DefaultClientConfigParameter, defaultClientConfig, ValidateStatus } from './helper';

// 默认的客户端和服务端配置数组，使用helper中的defaultClientConfigArray和defaultInternalConfigArray

// 客户端默认项，包含错误信息 authServer和matchUrl为空
export const clientConfigWithError = [
    {
        index: defaultClientConfig[DefaultClientConfigParameter.HideLogin].index,
        configName: DefaultClientConfigParameter.HideLogin,
        configType: defaultClientConfig[DefaultClientConfigParameter.HideLogin].configType,
        configValue: false,
        defaultConfig: true,
        valueRequired: defaultClientConfig[DefaultClientConfigParameter.HideLogin].valueRequired,
        nameValidateStatus: ValidateStatus.Normal,
        valueValidateStatus: ValidateStatus.Normal,
    },
    {
        index: defaultClientConfig[DefaultClientConfigParameter.HideThirdLogin].index,
        configName: DefaultClientConfigParameter.HideThirdLogin,
        configType: defaultClientConfig[DefaultClientConfigParameter.HideThirdLogin].configType,
        configValue: true,
        defaultConfig: true,
        valueRequired: defaultClientConfig[DefaultClientConfigParameter.HideThirdLogin].valueRequired,
        nameValidateStatus: ValidateStatus.Normal,
        valueValidateStatus: ValidateStatus.Normal,
    },
    {
        index: defaultClientConfig[DefaultClientConfigParameter.AuthServer].index,
        configName: DefaultClientConfigParameter.AuthServer,
        configType: defaultClientConfig[DefaultClientConfigParameter.AuthServer].configType,
        configValue: '',
        defaultConfig: true,
        valueRequired: defaultClientConfig[DefaultClientConfigParameter.AuthServer].valueRequired,
        nameValidateStatus: ValidateStatus.Normal,
        // 验证错误，不能为空
        valueValidateStatus: ValidateStatus.Empty,
    },
    // {
    //     index: defaultClientConfig[DefaultClientConfigParameter.AutoCasRedirect].index,
    //     configName: DefaultClientConfigParameter.AutoCasRedirect,
    //     configType: defaultClientConfig[DefaultClientConfigParameter.AutoCasRedirect].configType,
    //     configValue: false,
    //     defaultConfig: true,
    //     valueRequired: defaultClientConfig[DefaultClientConfigParameter.AutoCasRedirect].valueRequired,
    //     nameValidateStatus: ValidateStatus.Normal,
    //     valueValidateStatus: ValidateStatus.Normal,
    // },
    {
        index: defaultClientConfig[DefaultClientConfigParameter.MatchUrl].index,
        configName: DefaultClientConfigParameter.MatchUrl,
        configType: defaultClientConfig[DefaultClientConfigParameter.MatchUrl].configType,
        configValue: '',
        defaultConfig: true,
        valueRequired: defaultClientConfig[DefaultClientConfigParameter.MatchUrl].valueRequired,
        nameValidateStatus: ValidateStatus.Normal,
        // 验证错误，不能为空
        valueValidateStatus: ValidateStatus.Empty,
    },
    // {
    //     index: defaultClientConfig[DefaultClientConfigParameter.LoginButtonText].index,
    //     configName: DefaultClientConfigParameter.LoginButtonText,
    //     configType: defaultClientConfig[DefaultClientConfigParameter.LoginButtonText].configType,
    //     configValue: '',
    //     defaultConfig: true,
    //     valueRequired: defaultClientConfig[DefaultClientConfigParameter.LoginButtonText].valueRequired,
    //     nameValidateStatus: ValidateStatus.Normal,
    //     valueValidateStatus: ValidateStatus.Normal,
    // },
    // {
    //     index: defaultClientConfig[DefaultClientConfigParameter.LogoutUrl].index,
    //     configName: DefaultClientConfigParameter.LogoutUrl,
    //     configType: defaultClientConfig[DefaultClientConfigParameter.LogoutUrl].configType,
    //     configValue: '',
    //     defaultConfig: true,
    //     valueRequired: defaultClientConfig[DefaultClientConfigParameter.LogoutUrl].valueRequired,
    //     nameValidateStatus: ValidateStatus.Normal,
    //     valueValidateStatus: ValidateStatus.Normal,
    // },
    // {
    //     index: defaultClientConfig[DefaultClientConfigParameter.AppId].index,
    //     configName: DefaultClientConfigParameter.AppId,
    //     configType: defaultClientConfig[DefaultClientConfigParameter.AppId].configType,
    //     configValue: '',
    //     defaultConfig: true,
    //     valueRequired: defaultClientConfig[DefaultClientConfigParameter.AppId].valueRequired,
    //     nameValidateStatus: ValidateStatus.Normal,
    //     valueValidateStatus: ValidateStatus.Normal,
    // },
    // {
    //     index: defaultClientConfig[DefaultClientConfigParameter.AppKey].index,
    //     configName: DefaultClientConfigParameter.AppKey,
    //     configType: defaultClientConfig[DefaultClientConfigParameter.AppKey].configType,
    //     configValue: '',
    //     defaultConfig: true,
    //     valueRequired: defaultClientConfig[DefaultClientConfigParameter.AppKey].valueRequired,
    //     nameValidateStatus: ValidateStatus.Normal,
    //     valueValidateStatus: ValidateStatus.Normal,
    // },
]

// 客户端默认项，修复了 authServer 错误，matchUrl依旧为空
export const clientConfigAuthServerFixed = [
    {
        index: defaultClientConfig[DefaultClientConfigParameter.HideLogin].index,
        configName: DefaultClientConfigParameter.HideLogin,
        configType: defaultClientConfig[DefaultClientConfigParameter.HideLogin].configType,
        configValue: false,
        defaultConfig: true,
        valueRequired: defaultClientConfig[DefaultClientConfigParameter.HideLogin].valueRequired,
        nameValidateStatus: ValidateStatus.Normal,
        valueValidateStatus: ValidateStatus.Normal,
    },
    {
        index: defaultClientConfig[DefaultClientConfigParameter.HideThirdLogin].index,
        configName: DefaultClientConfigParameter.HideThirdLogin,
        configType: defaultClientConfig[DefaultClientConfigParameter.HideThirdLogin].configType,
        configValue: true,
        defaultConfig: true,
        valueRequired: defaultClientConfig[DefaultClientConfigParameter.HideThirdLogin].valueRequired,
        nameValidateStatus: ValidateStatus.Normal,
        valueValidateStatus: ValidateStatus.Normal,
    },
    {
        index: defaultClientConfig[DefaultClientConfigParameter.AuthServer].index,
        configName: DefaultClientConfigParameter.AuthServer,
        configType: defaultClientConfig[DefaultClientConfigParameter.AuthServer].configType,
        configValue: 'http://192.168.138.28',
        defaultConfig: true,
        valueRequired: defaultClientConfig[DefaultClientConfigParameter.AuthServer].valueRequired,
        nameValidateStatus: ValidateStatus.Normal,
        valueValidateStatus: ValidateStatus.Normal,
    },
    // {
    //     index: defaultClientConfig[DefaultClientConfigParameter.AutoCasRedirect].index,
    //     configName: DefaultClientConfigParameter.AutoCasRedirect,
    //     configType: defaultClientConfig[DefaultClientConfigParameter.AutoCasRedirect].configType,
    //     configValue: false,
    //     defaultConfig: true,
    //     valueRequired: defaultClientConfig[DefaultClientConfigParameter.AutoCasRedirect].valueRequired,
    //     nameValidateStatus: ValidateStatus.Normal,
    //     valueValidateStatus: ValidateStatus.Normal,
    // },
    {
        index: defaultClientConfig[DefaultClientConfigParameter.MatchUrl].index,
        configName: DefaultClientConfigParameter.MatchUrl,
        configType: defaultClientConfig[DefaultClientConfigParameter.MatchUrl].configType,
        configValue: '',
        defaultConfig: true,
        valueRequired: defaultClientConfig[DefaultClientConfigParameter.MatchUrl].valueRequired,
        nameValidateStatus: ValidateStatus.Normal,
        valueValidateStatus: ValidateStatus.Empty,
    },
    // {
    //     index: defaultClientConfig[DefaultClientConfigParameter.LoginButtonText].index,
    //     configName: DefaultClientConfigParameter.LoginButtonText,
    //     configType: defaultClientConfig[DefaultClientConfigParameter.LoginButtonText].configType,
    //     configValue: '',
    //     defaultConfig: true,
    //     valueRequired: defaultClientConfig[DefaultClientConfigParameter.LoginButtonText].valueRequired,
    //     nameValidateStatus: ValidateStatus.Normal,
    //     valueValidateStatus: ValidateStatus.Normal,
    // },
    // {
    //     index: defaultClientConfig[DefaultClientConfigParameter.LogoutUrl].index,
    //     configName: DefaultClientConfigParameter.LogoutUrl,
    //     configType: defaultClientConfig[DefaultClientConfigParameter.LogoutUrl].configType,
    //     configValue: '',
    //     defaultConfig: true,
    //     valueRequired: defaultClientConfig[DefaultClientConfigParameter.LogoutUrl].valueRequired,
    //     nameValidateStatus: ValidateStatus.Normal,
    //     valueValidateStatus: ValidateStatus.Normal,
    // },
    // {
    //     index: defaultClientConfig[DefaultClientConfigParameter.AppId].index,
    //     configName: DefaultClientConfigParameter.AppId,
    //     configType: defaultClientConfig[DefaultClientConfigParameter.AppId].configType,
    //     configValue: '',
    //     defaultConfig: true,
    //     valueRequired: defaultClientConfig[DefaultClientConfigParameter.AppId].valueRequired,
    //     nameValidateStatus: ValidateStatus.Normal,
    //     valueValidateStatus: ValidateStatus.Normal,
    // },
    // {
    //     index: defaultClientConfig[DefaultClientConfigParameter.AppKey].index,
    //     configName: DefaultClientConfigParameter.AppKey,
    //     configType: defaultClientConfig[DefaultClientConfigParameter.AppKey].configType,
    //     configValue: '',
    //     defaultConfig: true,
    //     valueRequired: defaultClientConfig[DefaultClientConfigParameter.AppKey].valueRequired,
    //     nameValidateStatus: ValidateStatus.Normal,
    //     valueValidateStatus: ValidateStatus.Normal,
    // },
]

// 有效配置，只包含客户端默认项
export const validClientConfigOnlyDefault = [
    {
        index: defaultClientConfig[DefaultClientConfigParameter.HideLogin].index,
        configName: DefaultClientConfigParameter.HideLogin,
        configType: defaultClientConfig[DefaultClientConfigParameter.HideLogin].configType,
        configValue: false,
        defaultConfig: true,
        valueRequired: defaultClientConfig[DefaultClientConfigParameter.HideLogin].valueRequired,
        nameValidateStatus: ValidateStatus.Normal,
        valueValidateStatus: ValidateStatus.Normal,
    },
    {
        index: defaultClientConfig[DefaultClientConfigParameter.HideThirdLogin].index,
        configName: DefaultClientConfigParameter.HideThirdLogin,
        configType: defaultClientConfig[DefaultClientConfigParameter.HideThirdLogin].configType,
        configValue: true,
        defaultConfig: true,
        valueRequired: defaultClientConfig[DefaultClientConfigParameter.HideThirdLogin].valueRequired,
        nameValidateStatus: ValidateStatus.Normal,
        valueValidateStatus: ValidateStatus.Normal,
    },
    {
        index: defaultClientConfig[DefaultClientConfigParameter.AuthServer].index,
        configName: DefaultClientConfigParameter.AuthServer,
        configType: defaultClientConfig[DefaultClientConfigParameter.AuthServer].configType,
        configValue: 'http://192.168.138.28',
        defaultConfig: true,
        valueRequired: defaultClientConfig[DefaultClientConfigParameter.AuthServer].valueRequired,
        nameValidateStatus: ValidateStatus.Normal,
        valueValidateStatus: ValidateStatus.Normal,
    },
    // {
    //     index: defaultClientConfig[DefaultClientConfigParameter.AutoCasRedirect].index,
    //     configName: DefaultClientConfigParameter.AutoCasRedirect,
    //     configType: defaultClientConfig[DefaultClientConfigParameter.AutoCasRedirect].configType,
    //     configValue: false,
    //     defaultConfig: true,
    //     valueRequired: defaultClientConfig[DefaultClientConfigParameter.AutoCasRedirect].valueRequired,
    //     nameValidateStatus: ValidateStatus.Normal,
    //     valueValidateStatus: ValidateStatus.Normal,
    // },
    {
        index: defaultClientConfig[DefaultClientConfigParameter.MatchUrl].index,
        configName: DefaultClientConfigParameter.MatchUrl,
        configType: defaultClientConfig[DefaultClientConfigParameter.MatchUrl].configType,
        configValue: 'http://192.168.138.28',
        defaultConfig: true,
        valueRequired: defaultClientConfig[DefaultClientConfigParameter.MatchUrl].valueRequired,
        nameValidateStatus: ValidateStatus.Normal,
        valueValidateStatus: ValidateStatus.Normal,
    },
    // {
    //     index: defaultClientConfig[DefaultClientConfigParameter.LoginButtonText].index,
    //     configName: DefaultClientConfigParameter.LoginButtonText,
    //     configType: defaultClientConfig[DefaultClientConfigParameter.LoginButtonText].configType,
    //     configValue: '',
    //     defaultConfig: true,
    //     valueRequired: defaultClientConfig[DefaultClientConfigParameter.LoginButtonText].valueRequired,
    //     nameValidateStatus: ValidateStatus.Normal,
    //     valueValidateStatus: ValidateStatus.Normal,
    // },
    // {
    //     index: defaultClientConfig[DefaultClientConfigParameter.LogoutUrl].index,
    //     configName: DefaultClientConfigParameter.LogoutUrl,
    //     configType: defaultClientConfig[DefaultClientConfigParameter.LogoutUrl].configType,
    //     configValue: '',
    //     defaultConfig: true,
    //     valueRequired: defaultClientConfig[DefaultClientConfigParameter.LogoutUrl].valueRequired,
    //     nameValidateStatus: ValidateStatus.Normal,
    //     valueValidateStatus: ValidateStatus.Normal,
    // },
    // {
    //     index: defaultClientConfig[DefaultClientConfigParameter.AppId].index,
    //     configName: DefaultClientConfigParameter.AppId,
    //     configType: defaultClientConfig[DefaultClientConfigParameter.AppId].configType,
    //     configValue: '',
    //     defaultConfig: true,
    //     valueRequired: defaultClientConfig[DefaultClientConfigParameter.AppId].valueRequired,
    //     nameValidateStatus: ValidateStatus.Normal,
    //     valueValidateStatus: ValidateStatus.Normal,
    // },
    // {
    //     index: defaultClientConfig[DefaultClientConfigParameter.AppKey].index,
    //     configName: DefaultClientConfigParameter.AppKey,
    //     configType: defaultClientConfig[DefaultClientConfigParameter.AppKey].configType,
    //     configValue: '',
    //     defaultConfig: true,
    //     valueRequired: defaultClientConfig[DefaultClientConfigParameter.AppKey].valueRequired,
    //     nameValidateStatus: ValidateStatus.Normal,
    //     valueValidateStatus: ValidateStatus.Normal,
    // },
]

// 客户端默认配置项-对象格式
export const clientConfig = {
    hideLogin: false,
    hideThirdLogin: true,
    authServer: 'http://192.168.138.28',
    // autoCasRedirect: false,
    matchUrl: 'http://192.168.138.28',
    // loginButtonText: '',
    // logoutUrl: '',
    // appId: '',
    // appKey: '',
}

// 客户端默认配置项-对象格式
export const internalConfig = {
    // ouModule: '',
    syncModule: 'BaseSyncer',
    // authModule: '',
    // syncInterval: 1800,
    // userCreateStatus: true,
    // validPeriod: -1,
}

// 客户端默认配置项-JSON格式
export const clientConfigString = `{"hideLogin":false,"hideThirdLogin":true,"authServer":"http://192.168.138.28","matchUrl":"http://192.168.138.28"}`

// 服务端默认配置项-JSON格式
export const internalConfigString = `{"syncModule":"BaseSyncer"}`