// Code generated by Thrift Compiler (0.19.0). DO NOT EDIT.

package ethriftexception

import (
	"bytes"
	"context"
	"errors"
	"fmt"
	"time"
	thrift "github.com/kweaver-ai/go-lib/thrift"
	"strings"
	"regexp"
)

// (needed to ensure safety because of naive import list construction.)
var _ = thrift.ZERO
var _ = fmt.Printf
var _ = errors.New
var _ = context.Background
var _ = time.Now
var _ = bytes.Equal
// (needed by validator.)
var _ = strings.Contains
var _ = regexp.MatchString


func init() {
}

