// Code generated by MockGen. DO NOT EDIT.
// Source: /root/GoCommon/api/mqclient.go

// Package mock_msqclient is a generated GoMock package.
package mock_msqclient

import (
	reflect "reflect"

	gomock "go.uber.org/mock/gomock"
)

// MockMQClient is a mock of MQClient interface.
type MockMQClient struct {
	ctrl     *gomock.Controller
	recorder *MockMQClientMockRecorder
}

// MockMQClientMockRecorder is the mock recorder for MockMQClient.
type MockMQClientMockRecorder struct {
	mock *MockMQClient
}

// NewMockMQClient creates a new mock instance.
func NewMockMQClient(ctrl *gomock.Controller) *MockMQClient {
	mock := &MockMQClient{ctrl: ctrl}
	mock.recorder = &MockMQClientMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockMQClient) EXPECT() *MockMQClientMockRecorder {
	return m.recorder
}

// Publish mocks base method.
func (m *MockMQClient) Publish(arg0 string, arg1 []byte) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Publish", arg0, arg1)
	ret0, _ := ret[0].(error)
	return ret0
}

// Publish indicates an expected call of Publish.
func (mr *MockMQClientMockRecorder) Publish(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Publish", reflect.TypeOf((*MockMQClient)(nil).Publish), arg0, arg1)
}

// Subscribe mocks base method.
func (m *MockMQClient) Subscribe(topic, channel string, cmd func([]byte) error) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "Subscribe", topic, channel, cmd)
}

// Subscribe indicates an expected call of Subscribe.
func (mr *MockMQClientMockRecorder) Subscribe(topic, channel, cmd interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Subscribe", reflect.TypeOf((*MockMQClient)(nil).Subscribe), topic, channel, cmd)
}
