// Code generated by Thrift Compiler (0.19.0). DO NOT EDIT.

package ethriftexception

import (
	"bytes"
	"context"
	"database/sql/driver"
	"errors"
	"fmt"
	"time"
	thrift "github.com/kweaver-ai/go-lib/thrift"
	"strings"
	"regexp"
)

// (needed to ensure safety because of naive import list construction.)
var _ = thrift.ZERO
var _ = fmt.Printf
var _ = errors.New
var _ = context.Background
var _ = time.Now
var _ = bytes.Equal
// (needed by validator.)
var _ = strings.Contains
var _ = regexp.MatchString

//异常类型枚举类型
type NcTExpType int64
const (
  NcTExpType_NCT_FATAL NcTExpType = 0
  NcTExpType_NCT_CRITICAL NcTExpType = 1
  NcTExpType_NCT_WARN NcTExpType = 2
  NcTExpType_NCT_INFO NcTExpType = 3
)

func (p NcTExpType) String() string {
  switch p {
  case NcTExpType_NCT_FATAL: return "NCT_FATAL"
  case NcTExpType_NCT_CRITICAL: return "NCT_CRITICAL"
  case NcTExpType_NCT_WARN: return "NCT_WARN"
  case NcTExpType_NCT_INFO: return "NCT_INFO"
  }
  return "<UNSET>"
}

func NcTExpTypeFromString(s string) (NcTExpType, error) {
  switch s {
  case "NCT_FATAL": return NcTExpType_NCT_FATAL, nil 
  case "NCT_CRITICAL": return NcTExpType_NCT_CRITICAL, nil 
  case "NCT_WARN": return NcTExpType_NCT_WARN, nil 
  case "NCT_INFO": return NcTExpType_NCT_INFO, nil 
  }
  return NcTExpType(0), fmt.Errorf("not a valid NcTExpType string")
}


func NcTExpTypePtr(v NcTExpType) *NcTExpType { return &v }

func (p NcTExpType) MarshalText() ([]byte, error) {
return []byte(p.String()), nil
}

func (p *NcTExpType) UnmarshalText(text []byte) error {
q, err := NcTExpTypeFromString(string(text))
if (err != nil) {
return err
}
*p = q
return nil
}

func (p *NcTExpType) Scan(value interface{}) error {
v, ok := value.(int64)
if !ok {
return errors.New("Scan value is not int64")
}
*p = NcTExpType(v)
return nil
}

func (p * NcTExpType) Value() (driver.Value, error) {
  if p == nil {
    return nil, nil
  }
return int64(*p), nil
}
// 异常具体内容
// 
// Attributes:
//  - ExpType
//  - CodeLine
//  - ErrID
//  - FileName
//  - ExpMsg
//  - ErrProvider
//  - Time
//  - ErrDetail
type NcTException struct {
  ExpType NcTExpType `thrift:"expType,1,required" db:"expType" json:"expType"`
  CodeLine int32 `thrift:"codeLine,2,required" db:"codeLine" json:"codeLine"`
  ErrID int32 `thrift:"errID,3,required" db:"errID" json:"errID"`
  FileName string `thrift:"fileName,4,required" db:"fileName" json:"fileName"`
  ExpMsg string `thrift:"expMsg,5,required" db:"expMsg" json:"expMsg"`
  ErrProvider string `thrift:"errProvider,6,required" db:"errProvider" json:"errProvider"`
  Time string `thrift:"time,7,required" db:"time" json:"time"`
  ErrDetail string `thrift:"errDetail,8,required" db:"errDetail" json:"errDetail"`
}

func NewNcTException() *NcTException {
  return &NcTException{}
}


func (p *NcTException) GetExpType() NcTExpType {
  return p.ExpType
}

func (p *NcTException) GetCodeLine() int32 {
  return p.CodeLine
}

func (p *NcTException) GetErrID() int32 {
  return p.ErrID
}

func (p *NcTException) GetFileName() string {
  return p.FileName
}

func (p *NcTException) GetExpMsg() string {
  return p.ExpMsg
}

func (p *NcTException) GetErrProvider() string {
  return p.ErrProvider
}

func (p *NcTException) GetTime() string {
  return p.Time
}

func (p *NcTException) GetErrDetail() string {
  return p.ErrDetail
}
func (p *NcTException) Read(ctx context.Context, iprot thrift.TProtocol) error {
  if _, err := iprot.ReadStructBegin(ctx); err != nil {
    return thrift.PrependError(fmt.Sprintf("%T read error: ", p), err)
  }

  var issetExpType bool = false;
  var issetCodeLine bool = false;
  var issetErrID bool = false;
  var issetFileName bool = false;
  var issetExpMsg bool = false;
  var issetErrProvider bool = false;
  var issetTime bool = false;
  var issetErrDetail bool = false;

  for {
    _, fieldTypeId, fieldId, err := iprot.ReadFieldBegin(ctx)
    if err != nil {
      return thrift.PrependError(fmt.Sprintf("%T field %d read error: ", p, fieldId), err)
    }
    if fieldTypeId == thrift.STOP { break; }
    switch fieldId {
    case 1:
      if fieldTypeId == thrift.I32 {
        if err := p.ReadField1(ctx, iprot); err != nil {
          return err
        }
        issetExpType = true
      } else {
        if err := iprot.Skip(ctx, fieldTypeId); err != nil {
          return err
        }
      }
    case 2:
      if fieldTypeId == thrift.I32 {
        if err := p.ReadField2(ctx, iprot); err != nil {
          return err
        }
        issetCodeLine = true
      } else {
        if err := iprot.Skip(ctx, fieldTypeId); err != nil {
          return err
        }
      }
    case 3:
      if fieldTypeId == thrift.I32 {
        if err := p.ReadField3(ctx, iprot); err != nil {
          return err
        }
        issetErrID = true
      } else {
        if err := iprot.Skip(ctx, fieldTypeId); err != nil {
          return err
        }
      }
    case 4:
      if fieldTypeId == thrift.STRING {
        if err := p.ReadField4(ctx, iprot); err != nil {
          return err
        }
        issetFileName = true
      } else {
        if err := iprot.Skip(ctx, fieldTypeId); err != nil {
          return err
        }
      }
    case 5:
      if fieldTypeId == thrift.STRING {
        if err := p.ReadField5(ctx, iprot); err != nil {
          return err
        }
        issetExpMsg = true
      } else {
        if err := iprot.Skip(ctx, fieldTypeId); err != nil {
          return err
        }
      }
    case 6:
      if fieldTypeId == thrift.STRING {
        if err := p.ReadField6(ctx, iprot); err != nil {
          return err
        }
        issetErrProvider = true
      } else {
        if err := iprot.Skip(ctx, fieldTypeId); err != nil {
          return err
        }
      }
    case 7:
      if fieldTypeId == thrift.STRING {
        if err := p.ReadField7(ctx, iprot); err != nil {
          return err
        }
        issetTime = true
      } else {
        if err := iprot.Skip(ctx, fieldTypeId); err != nil {
          return err
        }
      }
    case 8:
      if fieldTypeId == thrift.STRING {
        if err := p.ReadField8(ctx, iprot); err != nil {
          return err
        }
        issetErrDetail = true
      } else {
        if err := iprot.Skip(ctx, fieldTypeId); err != nil {
          return err
        }
      }
    default:
      if err := iprot.Skip(ctx, fieldTypeId); err != nil {
        return err
      }
    }
    if err := iprot.ReadFieldEnd(ctx); err != nil {
      return err
    }
  }
  if err := iprot.ReadStructEnd(ctx); err != nil {
    return thrift.PrependError(fmt.Sprintf("%T read struct end error: ", p), err)
  }
  if !issetExpType{
    return thrift.NewTProtocolExceptionWithType(thrift.INVALID_DATA, fmt.Errorf("Required field ExpType is not set"));
  }
  if !issetCodeLine{
    return thrift.NewTProtocolExceptionWithType(thrift.INVALID_DATA, fmt.Errorf("Required field CodeLine is not set"));
  }
  if !issetErrID{
    return thrift.NewTProtocolExceptionWithType(thrift.INVALID_DATA, fmt.Errorf("Required field ErrID is not set"));
  }
  if !issetFileName{
    return thrift.NewTProtocolExceptionWithType(thrift.INVALID_DATA, fmt.Errorf("Required field FileName is not set"));
  }
  if !issetExpMsg{
    return thrift.NewTProtocolExceptionWithType(thrift.INVALID_DATA, fmt.Errorf("Required field ExpMsg is not set"));
  }
  if !issetErrProvider{
    return thrift.NewTProtocolExceptionWithType(thrift.INVALID_DATA, fmt.Errorf("Required field ErrProvider is not set"));
  }
  if !issetTime{
    return thrift.NewTProtocolExceptionWithType(thrift.INVALID_DATA, fmt.Errorf("Required field Time is not set"));
  }
  if !issetErrDetail{
    return thrift.NewTProtocolExceptionWithType(thrift.INVALID_DATA, fmt.Errorf("Required field ErrDetail is not set"));
  }
  return nil
}

func (p *NcTException)  ReadField1(ctx context.Context, iprot thrift.TProtocol) error {
  if v, err := iprot.ReadI32(ctx); err != nil {
  return thrift.PrependError("error reading field 1: ", err)
} else {
  temp := NcTExpType(v)
  p.ExpType = temp
}
  return nil
}

func (p *NcTException)  ReadField2(ctx context.Context, iprot thrift.TProtocol) error {
  if v, err := iprot.ReadI32(ctx); err != nil {
  return thrift.PrependError("error reading field 2: ", err)
} else {
  p.CodeLine = v
}
  return nil
}

func (p *NcTException)  ReadField3(ctx context.Context, iprot thrift.TProtocol) error {
  if v, err := iprot.ReadI32(ctx); err != nil {
  return thrift.PrependError("error reading field 3: ", err)
} else {
  p.ErrID = v
}
  return nil
}

func (p *NcTException)  ReadField4(ctx context.Context, iprot thrift.TProtocol) error {
  if v, err := iprot.ReadString(ctx); err != nil {
  return thrift.PrependError("error reading field 4: ", err)
} else {
  p.FileName = v
}
  return nil
}

func (p *NcTException)  ReadField5(ctx context.Context, iprot thrift.TProtocol) error {
  if v, err := iprot.ReadString(ctx); err != nil {
  return thrift.PrependError("error reading field 5: ", err)
} else {
  p.ExpMsg = v
}
  return nil
}

func (p *NcTException)  ReadField6(ctx context.Context, iprot thrift.TProtocol) error {
  if v, err := iprot.ReadString(ctx); err != nil {
  return thrift.PrependError("error reading field 6: ", err)
} else {
  p.ErrProvider = v
}
  return nil
}

func (p *NcTException)  ReadField7(ctx context.Context, iprot thrift.TProtocol) error {
  if v, err := iprot.ReadString(ctx); err != nil {
  return thrift.PrependError("error reading field 7: ", err)
} else {
  p.Time = v
}
  return nil
}

func (p *NcTException)  ReadField8(ctx context.Context, iprot thrift.TProtocol) error {
  if v, err := iprot.ReadString(ctx); err != nil {
  return thrift.PrependError("error reading field 8: ", err)
} else {
  p.ErrDetail = v
}
  return nil
}

func (p *NcTException) Write(ctx context.Context, oprot thrift.TProtocol) error {
  if err := oprot.WriteStructBegin(ctx, "ncTException"); err != nil {
    return thrift.PrependError(fmt.Sprintf("%T write struct begin error: ", p), err) }
  if p != nil {
    if err := p.writeField1(ctx, oprot); err != nil { return err }
    if err := p.writeField2(ctx, oprot); err != nil { return err }
    if err := p.writeField3(ctx, oprot); err != nil { return err }
    if err := p.writeField4(ctx, oprot); err != nil { return err }
    if err := p.writeField5(ctx, oprot); err != nil { return err }
    if err := p.writeField6(ctx, oprot); err != nil { return err }
    if err := p.writeField7(ctx, oprot); err != nil { return err }
    if err := p.writeField8(ctx, oprot); err != nil { return err }
  }
  if err := oprot.WriteFieldStop(ctx); err != nil {
    return thrift.PrependError("write field stop error: ", err) }
  if err := oprot.WriteStructEnd(ctx); err != nil {
    return thrift.PrependError("write struct stop error: ", err) }
  return nil
}

func (p *NcTException) writeField1(ctx context.Context, oprot thrift.TProtocol) (err error) {
  if err := oprot.WriteFieldBegin(ctx, "expType", thrift.I32, 1); err != nil {
    return thrift.PrependError(fmt.Sprintf("%T write field begin error 1:expType: ", p), err) }
  if err := oprot.WriteI32(ctx, int32(p.ExpType)); err != nil {
  return thrift.PrependError(fmt.Sprintf("%T.expType (1) field write error: ", p), err) }
  if err := oprot.WriteFieldEnd(ctx); err != nil {
    return thrift.PrependError(fmt.Sprintf("%T write field end error 1:expType: ", p), err) }
  return err
}

func (p *NcTException) writeField2(ctx context.Context, oprot thrift.TProtocol) (err error) {
  if err := oprot.WriteFieldBegin(ctx, "codeLine", thrift.I32, 2); err != nil {
    return thrift.PrependError(fmt.Sprintf("%T write field begin error 2:codeLine: ", p), err) }
  if err := oprot.WriteI32(ctx, int32(p.CodeLine)); err != nil {
  return thrift.PrependError(fmt.Sprintf("%T.codeLine (2) field write error: ", p), err) }
  if err := oprot.WriteFieldEnd(ctx); err != nil {
    return thrift.PrependError(fmt.Sprintf("%T write field end error 2:codeLine: ", p), err) }
  return err
}

func (p *NcTException) writeField3(ctx context.Context, oprot thrift.TProtocol) (err error) {
  if err := oprot.WriteFieldBegin(ctx, "errID", thrift.I32, 3); err != nil {
    return thrift.PrependError(fmt.Sprintf("%T write field begin error 3:errID: ", p), err) }
  if err := oprot.WriteI32(ctx, int32(p.ErrID)); err != nil {
  return thrift.PrependError(fmt.Sprintf("%T.errID (3) field write error: ", p), err) }
  if err := oprot.WriteFieldEnd(ctx); err != nil {
    return thrift.PrependError(fmt.Sprintf("%T write field end error 3:errID: ", p), err) }
  return err
}

func (p *NcTException) writeField4(ctx context.Context, oprot thrift.TProtocol) (err error) {
  if err := oprot.WriteFieldBegin(ctx, "fileName", thrift.STRING, 4); err != nil {
    return thrift.PrependError(fmt.Sprintf("%T write field begin error 4:fileName: ", p), err) }
  if err := oprot.WriteString(ctx, string(p.FileName)); err != nil {
  return thrift.PrependError(fmt.Sprintf("%T.fileName (4) field write error: ", p), err) }
  if err := oprot.WriteFieldEnd(ctx); err != nil {
    return thrift.PrependError(fmt.Sprintf("%T write field end error 4:fileName: ", p), err) }
  return err
}

func (p *NcTException) writeField5(ctx context.Context, oprot thrift.TProtocol) (err error) {
  if err := oprot.WriteFieldBegin(ctx, "expMsg", thrift.STRING, 5); err != nil {
    return thrift.PrependError(fmt.Sprintf("%T write field begin error 5:expMsg: ", p), err) }
  if err := oprot.WriteString(ctx, string(p.ExpMsg)); err != nil {
  return thrift.PrependError(fmt.Sprintf("%T.expMsg (5) field write error: ", p), err) }
  if err := oprot.WriteFieldEnd(ctx); err != nil {
    return thrift.PrependError(fmt.Sprintf("%T write field end error 5:expMsg: ", p), err) }
  return err
}

func (p *NcTException) writeField6(ctx context.Context, oprot thrift.TProtocol) (err error) {
  if err := oprot.WriteFieldBegin(ctx, "errProvider", thrift.STRING, 6); err != nil {
    return thrift.PrependError(fmt.Sprintf("%T write field begin error 6:errProvider: ", p), err) }
  if err := oprot.WriteString(ctx, string(p.ErrProvider)); err != nil {
  return thrift.PrependError(fmt.Sprintf("%T.errProvider (6) field write error: ", p), err) }
  if err := oprot.WriteFieldEnd(ctx); err != nil {
    return thrift.PrependError(fmt.Sprintf("%T write field end error 6:errProvider: ", p), err) }
  return err
}

func (p *NcTException) writeField7(ctx context.Context, oprot thrift.TProtocol) (err error) {
  if err := oprot.WriteFieldBegin(ctx, "time", thrift.STRING, 7); err != nil {
    return thrift.PrependError(fmt.Sprintf("%T write field begin error 7:time: ", p), err) }
  if err := oprot.WriteString(ctx, string(p.Time)); err != nil {
  return thrift.PrependError(fmt.Sprintf("%T.time (7) field write error: ", p), err) }
  if err := oprot.WriteFieldEnd(ctx); err != nil {
    return thrift.PrependError(fmt.Sprintf("%T write field end error 7:time: ", p), err) }
  return err
}

func (p *NcTException) writeField8(ctx context.Context, oprot thrift.TProtocol) (err error) {
  if err := oprot.WriteFieldBegin(ctx, "errDetail", thrift.STRING, 8); err != nil {
    return thrift.PrependError(fmt.Sprintf("%T write field begin error 8:errDetail: ", p), err) }
  if err := oprot.WriteString(ctx, string(p.ErrDetail)); err != nil {
  return thrift.PrependError(fmt.Sprintf("%T.errDetail (8) field write error: ", p), err) }
  if err := oprot.WriteFieldEnd(ctx); err != nil {
    return thrift.PrependError(fmt.Sprintf("%T write field end error 8:errDetail: ", p), err) }
  return err
}

func (p *NcTException) Equals(other *NcTException) bool {
  if p == other {
    return true
  } else if p == nil || other == nil {
    return false
  }
  if p.ExpType != other.ExpType { return false }
  if p.CodeLine != other.CodeLine { return false }
  if p.ErrID != other.ErrID { return false }
  if p.FileName != other.FileName { return false }
  if p.ExpMsg != other.ExpMsg { return false }
  if p.ErrProvider != other.ErrProvider { return false }
  if p.Time != other.Time { return false }
  if p.ErrDetail != other.ErrDetail { return false }
  return true
}

func (p *NcTException) String() string {
  if p == nil {
    return "<nil>"
  }
  return fmt.Sprintf("NcTException(%+v)", *p)
}

func (p *NcTException) Error() string {
  return p.String()
}

func (NcTException) TExceptionType() thrift.TExceptionType {
  return thrift.TExceptionTypeCompiled
}

var _ thrift.TException = (*NcTException)(nil)

func (p *NcTException) Validate() error {
  return nil
}
