// Code generated by MockGen. DO NOT EDIT.
// Source: devops.aishu.cn/AISHUDevOps/AnyShareFamily/_git/GoCommon/api (interfaces: Produce)

// Package mock_api is a generated GoMock package.
package mock_api

import (
	reflect "reflect"

	gomock "go.uber.org/mock/gomock"
)

// MockProduce is a mock of Produce interface
type MockProduce struct {
	ctrl     *gomock.Controller
	recorder *MockProduceMockRecorder
}

// MockProduceMockRecorder is the mock recorder for MockProduce
type MockProduceMockRecorder struct {
	mock *MockProduce
}

// NewMockProduce creates a new mock instance
func NewMockProduce(ctrl *gomock.Controller) *MockProduce {
	mock := &MockProduce{ctrl: ctrl}
	mock.recorder = &MockProduceMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use
func (m *MockProduce) EXPECT() *MockProduceMockRecorder {
	return m.recorder
}

// Publish mocks base method
func (m *MockProduce) Publish(arg0 string, arg1 []byte) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Publish", arg0, arg1)
	ret0, _ := ret[0].(error)
	return ret0
}

// Publish indicates an expected call of Publish
func (mr *MockProduceMockRecorder) Publish(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Publish", reflect.TypeOf((*MockProduce)(nil).Publish), arg0, arg1)
}
