// Code generated by MockGen. DO NOT EDIT.
// Source: ../api/oauth2.go

// Package mock_oauth2 is a generated GoMock package.
package mock_api

import (
	context "context"
	reflect "reflect"

	gomock "go.uber.org/mock/gomock"

	api "policy_mgnt/utils/gocommon/api"
)

// MockOAuth2 is a mock of OAuth2 interface.
type MockOAuth2 struct {
	ctrl     *gomock.Controller
	recorder *MockOAuth2MockRecorder
}

// MockOAuth2MockRecorder is the mock recorder for MockOAuth2.
type MockOAuth2MockRecorder struct {
	mock *MockOAuth2
}

// NewMockOAuth2 creates a new mock instance.
func NewMockOAuth2(ctrl *gomock.Controller) *MockOAuth2 {
	mock := &MockOAuth2{ctrl: ctrl}
	mock.recorder = &MockOAuth2MockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockOAuth2) EXPECT() *MockOAuth2MockRecorder {
	return m.recorder
}

// GetSelfClientInfo mocks base method.
func (m *MockOAuth2) GetSelfClientInfo(ctx context.Context) (string, string) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetSelfClientInfo", ctx)
	ret0, _ := ret[0].(string)
	ret1, _ := ret[1].(string)
	return ret0, ret1
}

// GetSelfClientInfo indicates an expected call of GetSelfClientInfo.
func (mr *MockOAuth2MockRecorder) GetSelfClientInfo(ctx interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetSelfClientInfo", reflect.TypeOf((*MockOAuth2)(nil).GetSelfClientInfo), ctx)
}

// GetSvcClientInfoByName mocks base method.
func (m *MockOAuth2) GetSvcClientInfoByName(ctx context.Context, name string) (string, string) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetSvcClientInfoByName", ctx, name)
	ret0, _ := ret[0].(string)
	ret1, _ := ret[1].(string)
	return ret0, ret1
}

// GetSvcClientInfoByName indicates an expected call of GetSvcClientInfoByName.
func (mr *MockOAuth2MockRecorder) GetSvcClientInfoByName(ctx, name interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetSvcClientInfoByName", reflect.TypeOf((*MockOAuth2)(nil).GetSvcClientInfoByName), ctx, name)
}

// InitInternalAccount mocks base method.
func (m *MockOAuth2) InitInternalAccount(name string, applyDocLibPerm, applyDocPerm []string) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "InitInternalAccount", name, applyDocLibPerm, applyDocPerm)
}

// InitInternalAccount indicates an expected call of InitInternalAccount.
func (mr *MockOAuth2MockRecorder) InitInternalAccount(name, applyDocLibPerm, applyDocPerm interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "InitInternalAccount", reflect.TypeOf((*MockOAuth2)(nil).InitInternalAccount), name, applyDocLibPerm, applyDocPerm)
}

// Introspection mocks base method.
func (m *MockOAuth2) Introspection(ctx context.Context, token string, scopes []string) (api.IntrospectionResult, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Introspection", ctx, token, scopes)
	ret0, _ := ret[0].(api.IntrospectionResult)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Introspection indicates an expected call of Introspection.
func (mr *MockOAuth2MockRecorder) Introspection(ctx, token, scopes interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Introspection", reflect.TypeOf((*MockOAuth2)(nil).Introspection), ctx, token, scopes)
}
