// Code generated by Thrift Compiler (0.19.0). DO NOT EDIT.

package main

import (
	"context"
	"flag"
	"fmt"
	"math"
	"net"
	"net/url"
	"os"
	"strconv"
	"strings"
	thrift "github.com/kweaver-ai/go-lib/thrift"
	"Authentication/tapi/ethriftexception"
	"Authentication/tapi/evfs"
)

var _ = ethriftexception.GoUnusedProtection__
var _ = evfs.GoUnusedProtection__

func Usage() {
  fmt.Fprintln(os.Stderr, "Usage of ", os.Args[0], " [-h host:port] [-u url] [-f[ramed]] function [arg1 [arg2...]]:")
  flag.PrintDefaults()
  fmt.Fprintln(os.Stderr, "\nFunctions:")
  fmt.Fprintln(os.Stderr, "  ncTEVFSGNSObjectSet GetSubObjectSet()")
  fmt.Fprintln(os.Stderr, "  void CreateDir(string gns, string dirName)")
  fmt.Fprintln(os.Stderr, "  ncTEVFSGNSObjectSet ListDirWithoutPermCheck(string gns)")
  fmt.Fprintln(os.Stderr, "  ncTEVFSGNSObjectSet ListFileWithoutPermCheck(string gns)")
  fmt.Fprintln(os.Stderr, "  string CopyWithoutPermCheck(string userId, string srcGns, string newParentGns, i32 ondup)")
  fmt.Fprintln(os.Stderr, "  bool CheckMgrObjectEmptyWithoutRecycleBin(string gns)")
  fmt.Fprintln(os.Stderr, "  string ConvertPath(string gns)")
  fmt.Fprintln(os.Stderr, "   ConvertPathByBatch( gnsList)")
  fmt.Fprintln(os.Stderr, "  string ConvertNamePath(string gns)")
  fmt.Fprintln(os.Stderr, "  void SetVersionMaxNum(i32 maxNum)")
  fmt.Fprintln(os.Stderr, "  i32 GetVersionMaxNum()")
  fmt.Fprintln(os.Stderr, "  void SetVersionBuildCycle(i32 buildCycle)")
  fmt.Fprintln(os.Stderr, "  i32 GetVersionBuildCycle()")
  fmt.Fprintln(os.Stderr, "  void SetLinkAccessCodeStatus(bool enable)")
  fmt.Fprintln(os.Stderr, "  bool GetLinkAccessCodeStatus()")
  fmt.Fprintln(os.Stderr, "  void SetLargeFileLimit(ncTEVFSLargeFileLimitConf conf)")
  fmt.Fprintln(os.Stderr, "  ncTEVFSLargeFileLimitConf GetLargeFileLimit()")
  fmt.Fprintln(os.Stderr, "  void SetFileSuffixLimit( suffixDocs)")
  fmt.Fprintln(os.Stderr, "   GetFileSuffixLimit()")
  fmt.Fprintln(os.Stderr, "  ncTETSResourceInfo GetETSResourceInfo(string gns)")
  fmt.Fprintln(os.Stderr, "   GetAllResourceInfo( gnsList)")
  fmt.Fprintln(os.Stderr, "  void ResetListCache()")
  fmt.Fprintln(os.Stderr, "  void EnableListCache()")
  fmt.Fprintln(os.Stderr, "  void DisableListCache()")
  fmt.Fprintln(os.Stderr, "  void EnableListCacheStats()")
  fmt.Fprintln(os.Stderr, "  void DisableListCacheStats()")
  fmt.Fprintln(os.Stderr, "  ncTEVFSListCacheInfo FetchListCacheInfo()")
  fmt.Fprintln(os.Stderr, "  ncTEVFSFilesCount GetCurrentFilesTotal()")
  fmt.Fprintln(os.Stderr, "   GetFilesTotal(ncTEVFSDate date, ncTEVFSDateUnit dateUnit)")
  fmt.Fprintln(os.Stderr, "   GetFilesChangeInfo(ncTEVFSDate date, ncTEVFSDateUnit dateUnit)")
  fmt.Fprintln(os.Stderr, "  ncTEVFSQuotaInfo FetchSpaceQuotaInfo(string cidGns)")
  fmt.Fprintln(os.Stderr, "  void SetQuotaInfo(string cidGns, i64 quota)")
  fmt.Fprintln(os.Stderr, "  i64 FetchOperatedInfo(ncTEVFSDate begDate, ncTEVFSDate endDate, ncTEVFSOperatedType opType)")
  fmt.Fprintln(os.Stderr, "   FetchAllOperatedInfo(ncTEVFSDate begDate, ncTEVFSDate endDate)")
  fmt.Fprintln(os.Stderr, "  bool GetRapidUploadSupport()")
  fmt.Fprintln(os.Stderr, "  void SetRapidUploadSupport(bool support)")
  fmt.Fprintln(os.Stderr, "  bool GetCrossOSSRapidUploadStatus()")
  fmt.Fprintln(os.Stderr, "  void SetCrossOSSRapidUploadStatus(bool enable)")
  fmt.Fprintln(os.Stderr, "  ncTEVFSRapidStatisInfo FetchRapidStatisInfo()")
  fmt.Fprintln(os.Stderr, "  i64 FetchTotalRapidFile(string fileName, i64 fileSizeMin, i64 fileSizeMax, i64 beginDate, i64 endDate)")
  fmt.Fprintln(os.Stderr, "   FetchRapidFilesInfo(string fileName, i64 fileSizeMin, i64 fileSizeMax, i64 beginDate, i64 endDate, i64 offset, i32 rows)")
  fmt.Fprintln(os.Stderr, "  i32 GetCSFLevel(string gns)")
  fmt.Fprintln(os.Stderr, "  i32 GetDirCSFLevel(string gns)")
  fmt.Fprintln(os.Stderr, "  void SetPreConvertEnable(bool enable)")
  fmt.Fprintln(os.Stderr, "  void ObjMeta_AddAppInfo(string appId, string appName)")
  fmt.Fprintln(os.Stderr, "   ObjMeta_GetAppInfos()")
  fmt.Fprintln(os.Stderr, "  void ObjMeta_SetAppName(string appId, string appName)")
  fmt.Fprintln(os.Stderr, "  void ObjMeta_SetAppStatus(string appId, i32 status)")
  fmt.Fprintln(os.Stderr, "  void ObjMeta_DeleteAppInfo(string appId)")
  fmt.Fprintln(os.Stderr, "  void SetUserDownloadLimitStatus(bool enable)")
  fmt.Fprintln(os.Stderr, "  bool GetUserDonwloadLimitStatus()")
  fmt.Fprintln(os.Stderr, "  void AddUserDownloadLimitInfos( limitInfos)")
  fmt.Fprintln(os.Stderr, "   GetUserDownloadLimitInfos()")
  fmt.Fprintln(os.Stderr, "  void DeleteUserDownloadLimitInfos( userIds)")
  fmt.Fprintln(os.Stderr, "   GetQuarantineFileList(ncTFiltrationParam filter, i64 start, i64 limit)")
  fmt.Fprintln(os.Stderr, "   GetFileVersionList(string docid, string key)")
  fmt.Fprintln(os.Stderr, "  i64 GetQuarantineFileCount(ncTFiltrationParam filter)")
  fmt.Fprintln(os.Stderr, "  ncTOSDowndloadRetParam OSDownload(string gns, string versionId, string authType, string reqHost, bool usehttps, string saveName)")
  fmt.Fprintln(os.Stderr, "  string RestoreQuarantineFile(string gns, i32 ondup)")
  fmt.Fprintln(os.Stderr, "  string DeleteQuarantineFile(string gns)")
  fmt.Fprintln(os.Stderr, "  ncTQuarantineRetMsg Quarantine(string docId, string reason, ncTEVFSQuarantineType type)")
  fmt.Fprintln(os.Stderr, "  ncTQuarantineConfig QRT_GetConfig()")
  fmt.Fprintln(os.Stderr, "  void QRT_SetAppealProtectTime(i32 days)")
  fmt.Fprintln(os.Stderr, "  void QRT_SetAutoDeleteTime(i32 days)")
  fmt.Fprintln(os.Stderr, "  string QRT_AppealApproval(string docid, bool approvalResult, i32 ondup, string appealSuggest)")
  fmt.Fprintln(os.Stderr, "  ncTEVFSFileInfoCount GetFileInfoCount(string name)")
  fmt.Fprintln(os.Stderr, "   GetPageFileInfo(ncTEVFSGetPageFileInfoParam param)")
  fmt.Fprintln(os.Stderr, "   GetFileRevisions(string docId)")
  fmt.Fprintln(os.Stderr, "  bool GetDocDueRemindStatus()")
  fmt.Fprintln(os.Stderr, "  void SetDocDueRemindStatus(bool enable)")
  fmt.Fprintln(os.Stderr, "  i32 GetDocDueRemindMsgSendTime()")
  fmt.Fprintln(os.Stderr, "  void SetDocDueRemindMsgSendTime(i32 hour)")
  fmt.Fprintln(os.Stderr, "  void SetNSQPubEnableStatus(bool enable)")
  fmt.Fprintln(os.Stderr, "  bool GetNSQPubEnableStatus()")
  fmt.Fprintln(os.Stderr, "  void EVFS_ThriftServerPing()")
  fmt.Fprintln(os.Stderr)
  os.Exit(0)
}

type httpHeaders map[string]string

func (h httpHeaders) String() string {
  var m map[string]string = h
  return fmt.Sprintf("%s", m)
}

func (h httpHeaders) Set(value string) error {
  parts := strings.Split(value, ": ")
  if len(parts) != 2 {
    return fmt.Errorf("header should be of format 'Key: Value'")
  }
  h[parts[0]] = parts[1]
  return nil
}

func main() {
  flag.Usage = Usage
  var host string
  var port int
  var protocol string
  var urlString string
  var framed bool
  var useHttp bool
  headers := make(httpHeaders)
  var parsedUrl *url.URL
  var trans thrift.TTransport
  _ = strconv.Atoi
  _ = math.Abs
  flag.Usage = Usage
  flag.StringVar(&host, "h", "localhost", "Specify host and port")
  flag.IntVar(&port, "p", 9090, "Specify port")
  flag.StringVar(&protocol, "P", "binary", "Specify the protocol (binary, compact, simplejson, json)")
  flag.StringVar(&urlString, "u", "", "Specify the url")
  flag.BoolVar(&framed, "framed", false, "Use framed transport")
  flag.BoolVar(&useHttp, "http", false, "Use http")
  flag.Var(headers, "H", "Headers to set on the http(s) request (e.g. -H \"Key: Value\")")
  flag.Parse()
  
  if len(urlString) > 0 {
    var err error
    parsedUrl, err = url.Parse(urlString)
    if err != nil {
      fmt.Fprintln(os.Stderr, "Error parsing URL: ", err)
      flag.Usage()
    }
    host = parsedUrl.Host
    useHttp = len(parsedUrl.Scheme) <= 0 || parsedUrl.Scheme == "http" || parsedUrl.Scheme == "https"
  } else if useHttp {
    _, err := url.Parse(fmt.Sprint("http://", host, ":", port))
    if err != nil {
      fmt.Fprintln(os.Stderr, "Error parsing URL: ", err)
      flag.Usage()
    }
  }
  
  cmd := flag.Arg(0)
  var err error
  var cfg *thrift.TConfiguration = nil
  if useHttp {
    trans, err = thrift.NewTHttpClient(parsedUrl.String())
    if len(headers) > 0 {
      httptrans := trans.(*thrift.THttpClient)
      for key, value := range headers {
        httptrans.SetHeader(key, value)
      }
    }
  } else {
    portStr := fmt.Sprint(port)
    if strings.Contains(host, ":") {
           host, portStr, err = net.SplitHostPort(host)
           if err != nil {
                   fmt.Fprintln(os.Stderr, "error with host:", err)
                   os.Exit(1)
           }
    }
    trans = thrift.NewTSocketConf(net.JoinHostPort(host, portStr), cfg)
    if err != nil {
      fmt.Fprintln(os.Stderr, "error resolving address:", err)
      os.Exit(1)
    }
    if framed {
      trans = thrift.NewTFramedTransportConf(trans, cfg)
    }
  }
  if err != nil {
    fmt.Fprintln(os.Stderr, "Error creating transport", err)
    os.Exit(1)
  }
  defer trans.Close()
  var protocolFactory thrift.TProtocolFactory
  switch protocol {
  case "compact":
    protocolFactory = thrift.NewTCompactProtocolFactoryConf(cfg)
    break
  case "simplejson":
    protocolFactory = thrift.NewTSimpleJSONProtocolFactoryConf(cfg)
    break
  case "json":
    protocolFactory = thrift.NewTJSONProtocolFactory()
    break
  case "binary", "":
    protocolFactory = thrift.NewTBinaryProtocolFactoryConf(cfg)
    break
  default:
    fmt.Fprintln(os.Stderr, "Invalid protocol specified: ", protocol)
    Usage()
    os.Exit(1)
  }
  iprot := protocolFactory.GetProtocol(trans)
  oprot := protocolFactory.GetProtocol(trans)
  client := evfs.NewNcTEVFSClient(thrift.NewTStandardClient(iprot, oprot))
  if err := trans.Open(); err != nil {
    fmt.Fprintln(os.Stderr, "Error opening socket to ", host, ":", port, " ", err)
    os.Exit(1)
  }
  
  switch cmd {
  case "GetSubObjectSet":
    if flag.NArg() - 1 != 0 {
      fmt.Fprintln(os.Stderr, "GetSubObjectSet requires 0 args")
      flag.Usage()
    }
    fmt.Print(client.GetSubObjectSet(context.Background()))
    fmt.Print("\n")
    break
  case "CreateDir":
    if flag.NArg() - 1 != 2 {
      fmt.Fprintln(os.Stderr, "CreateDir requires 2 args")
      flag.Usage()
    }
    argvalue0 := flag.Arg(1)
    value0 := argvalue0
    argvalue1 := flag.Arg(2)
    value1 := argvalue1
    fmt.Print(client.CreateDir(context.Background(), value0, value1))
    fmt.Print("\n")
    break
  case "ListDirWithoutPermCheck":
    if flag.NArg() - 1 != 1 {
      fmt.Fprintln(os.Stderr, "ListDirWithoutPermCheck requires 1 args")
      flag.Usage()
    }
    argvalue0 := flag.Arg(1)
    value0 := argvalue0
    fmt.Print(client.ListDirWithoutPermCheck(context.Background(), value0))
    fmt.Print("\n")
    break
  case "ListFileWithoutPermCheck":
    if flag.NArg() - 1 != 1 {
      fmt.Fprintln(os.Stderr, "ListFileWithoutPermCheck requires 1 args")
      flag.Usage()
    }
    argvalue0 := flag.Arg(1)
    value0 := argvalue0
    fmt.Print(client.ListFileWithoutPermCheck(context.Background(), value0))
    fmt.Print("\n")
    break
  case "CopyWithoutPermCheck":
    if flag.NArg() - 1 != 4 {
      fmt.Fprintln(os.Stderr, "CopyWithoutPermCheck requires 4 args")
      flag.Usage()
    }
    argvalue0 := flag.Arg(1)
    value0 := argvalue0
    argvalue1 := flag.Arg(2)
    value1 := argvalue1
    argvalue2 := flag.Arg(3)
    value2 := argvalue2
    tmp3, err429 := (strconv.Atoi(flag.Arg(4)))
    if err429 != nil {
      Usage()
      return
    }
    argvalue3 := int32(tmp3)
    value3 := argvalue3
    fmt.Print(client.CopyWithoutPermCheck(context.Background(), value0, value1, value2, value3))
    fmt.Print("\n")
    break
  case "CheckMgrObjectEmptyWithoutRecycleBin":
    if flag.NArg() - 1 != 1 {
      fmt.Fprintln(os.Stderr, "CheckMgrObjectEmptyWithoutRecycleBin requires 1 args")
      flag.Usage()
    }
    argvalue0 := flag.Arg(1)
    value0 := argvalue0
    fmt.Print(client.CheckMgrObjectEmptyWithoutRecycleBin(context.Background(), value0))
    fmt.Print("\n")
    break
  case "ConvertPath":
    if flag.NArg() - 1 != 1 {
      fmt.Fprintln(os.Stderr, "ConvertPath requires 1 args")
      flag.Usage()
    }
    argvalue0 := flag.Arg(1)
    value0 := argvalue0
    fmt.Print(client.ConvertPath(context.Background(), value0))
    fmt.Print("\n")
    break
  case "ConvertPathByBatch":
    if flag.NArg() - 1 != 1 {
      fmt.Fprintln(os.Stderr, "ConvertPathByBatch requires 1 args")
      flag.Usage()
    }
    arg432 := flag.Arg(1)
    mbTrans433 := thrift.NewTMemoryBufferLen(len(arg432))
    defer mbTrans433.Close()
    _, err434 := mbTrans433.WriteString(arg432)
    if err434 != nil { 
      Usage()
      return
    }
    factory435 := thrift.NewTJSONProtocolFactory()
    jsProt436 := factory435.GetProtocol(mbTrans433)
    containerStruct0 := evfs.NewNcTEVFSConvertPathByBatchArgs()
    err437 := containerStruct0.ReadField1(context.Background(), jsProt436)
    if err437 != nil {
      Usage()
      return
    }
    argvalue0 := containerStruct0.GnsList
    value0 := argvalue0
    fmt.Print(client.ConvertPathByBatch(context.Background(), value0))
    fmt.Print("\n")
    break
  case "ConvertNamePath":
    if flag.NArg() - 1 != 1 {
      fmt.Fprintln(os.Stderr, "ConvertNamePath requires 1 args")
      flag.Usage()
    }
    argvalue0 := flag.Arg(1)
    value0 := argvalue0
    fmt.Print(client.ConvertNamePath(context.Background(), value0))
    fmt.Print("\n")
    break
  case "SetVersionMaxNum":
    if flag.NArg() - 1 != 1 {
      fmt.Fprintln(os.Stderr, "SetVersionMaxNum requires 1 args")
      flag.Usage()
    }
    tmp0, err439 := (strconv.Atoi(flag.Arg(1)))
    if err439 != nil {
      Usage()
      return
    }
    argvalue0 := int32(tmp0)
    value0 := argvalue0
    fmt.Print(client.SetVersionMaxNum(context.Background(), value0))
    fmt.Print("\n")
    break
  case "GetVersionMaxNum":
    if flag.NArg() - 1 != 0 {
      fmt.Fprintln(os.Stderr, "GetVersionMaxNum requires 0 args")
      flag.Usage()
    }
    fmt.Print(client.GetVersionMaxNum(context.Background()))
    fmt.Print("\n")
    break
  case "SetVersionBuildCycle":
    if flag.NArg() - 1 != 1 {
      fmt.Fprintln(os.Stderr, "SetVersionBuildCycle requires 1 args")
      flag.Usage()
    }
    tmp0, err440 := (strconv.Atoi(flag.Arg(1)))
    if err440 != nil {
      Usage()
      return
    }
    argvalue0 := int32(tmp0)
    value0 := argvalue0
    fmt.Print(client.SetVersionBuildCycle(context.Background(), value0))
    fmt.Print("\n")
    break
  case "GetVersionBuildCycle":
    if flag.NArg() - 1 != 0 {
      fmt.Fprintln(os.Stderr, "GetVersionBuildCycle requires 0 args")
      flag.Usage()
    }
    fmt.Print(client.GetVersionBuildCycle(context.Background()))
    fmt.Print("\n")
    break
  case "SetLinkAccessCodeStatus":
    if flag.NArg() - 1 != 1 {
      fmt.Fprintln(os.Stderr, "SetLinkAccessCodeStatus requires 1 args")
      flag.Usage()
    }
    argvalue0 := flag.Arg(1) == "true"
    value0 := argvalue0
    fmt.Print(client.SetLinkAccessCodeStatus(context.Background(), value0))
    fmt.Print("\n")
    break
  case "GetLinkAccessCodeStatus":
    if flag.NArg() - 1 != 0 {
      fmt.Fprintln(os.Stderr, "GetLinkAccessCodeStatus requires 0 args")
      flag.Usage()
    }
    fmt.Print(client.GetLinkAccessCodeStatus(context.Background()))
    fmt.Print("\n")
    break
  case "SetLargeFileLimit":
    if flag.NArg() - 1 != 1 {
      fmt.Fprintln(os.Stderr, "SetLargeFileLimit requires 1 args")
      flag.Usage()
    }
    arg442 := flag.Arg(1)
    mbTrans443 := thrift.NewTMemoryBufferLen(len(arg442))
    defer mbTrans443.Close()
    _, err444 := mbTrans443.WriteString(arg442)
    if err444 != nil {
      Usage()
      return
    }
    factory445 := thrift.NewTJSONProtocolFactory()
    jsProt446 := factory445.GetProtocol(mbTrans443)
    argvalue0 := evfs.NewNcTEVFSLargeFileLimitConf()
    err447 := argvalue0.Read(context.Background(), jsProt446)
    if err447 != nil {
      Usage()
      return
    }
    value0 := argvalue0
    fmt.Print(client.SetLargeFileLimit(context.Background(), value0))
    fmt.Print("\n")
    break
  case "GetLargeFileLimit":
    if flag.NArg() - 1 != 0 {
      fmt.Fprintln(os.Stderr, "GetLargeFileLimit requires 0 args")
      flag.Usage()
    }
    fmt.Print(client.GetLargeFileLimit(context.Background()))
    fmt.Print("\n")
    break
  case "SetFileSuffixLimit":
    if flag.NArg() - 1 != 1 {
      fmt.Fprintln(os.Stderr, "SetFileSuffixLimit requires 1 args")
      flag.Usage()
    }
    arg448 := flag.Arg(1)
    mbTrans449 := thrift.NewTMemoryBufferLen(len(arg448))
    defer mbTrans449.Close()
    _, err450 := mbTrans449.WriteString(arg448)
    if err450 != nil { 
      Usage()
      return
    }
    factory451 := thrift.NewTJSONProtocolFactory()
    jsProt452 := factory451.GetProtocol(mbTrans449)
    containerStruct0 := evfs.NewNcTEVFSSetFileSuffixLimitArgs()
    err453 := containerStruct0.ReadField1(context.Background(), jsProt452)
    if err453 != nil {
      Usage()
      return
    }
    argvalue0 := containerStruct0.SuffixDocs
    value0 := argvalue0
    fmt.Print(client.SetFileSuffixLimit(context.Background(), value0))
    fmt.Print("\n")
    break
  case "GetFileSuffixLimit":
    if flag.NArg() - 1 != 0 {
      fmt.Fprintln(os.Stderr, "GetFileSuffixLimit requires 0 args")
      flag.Usage()
    }
    fmt.Print(client.GetFileSuffixLimit(context.Background()))
    fmt.Print("\n")
    break
  case "GetETSResourceInfo":
    if flag.NArg() - 1 != 1 {
      fmt.Fprintln(os.Stderr, "GetETSResourceInfo requires 1 args")
      flag.Usage()
    }
    argvalue0 := flag.Arg(1)
    value0 := argvalue0
    fmt.Print(client.GetETSResourceInfo(context.Background(), value0))
    fmt.Print("\n")
    break
  case "GetAllResourceInfo":
    if flag.NArg() - 1 != 1 {
      fmt.Fprintln(os.Stderr, "GetAllResourceInfo requires 1 args")
      flag.Usage()
    }
    arg455 := flag.Arg(1)
    mbTrans456 := thrift.NewTMemoryBufferLen(len(arg455))
    defer mbTrans456.Close()
    _, err457 := mbTrans456.WriteString(arg455)
    if err457 != nil { 
      Usage()
      return
    }
    factory458 := thrift.NewTJSONProtocolFactory()
    jsProt459 := factory458.GetProtocol(mbTrans456)
    containerStruct0 := evfs.NewNcTEVFSGetAllResourceInfoArgs()
    err460 := containerStruct0.ReadField1(context.Background(), jsProt459)
    if err460 != nil {
      Usage()
      return
    }
    argvalue0 := containerStruct0.GnsList
    value0 := argvalue0
    fmt.Print(client.GetAllResourceInfo(context.Background(), value0))
    fmt.Print("\n")
    break
  case "ResetListCache":
    if flag.NArg() - 1 != 0 {
      fmt.Fprintln(os.Stderr, "ResetListCache requires 0 args")
      flag.Usage()
    }
    fmt.Print(client.ResetListCache(context.Background()))
    fmt.Print("\n")
    break
  case "EnableListCache":
    if flag.NArg() - 1 != 0 {
      fmt.Fprintln(os.Stderr, "EnableListCache requires 0 args")
      flag.Usage()
    }
    fmt.Print(client.EnableListCache(context.Background()))
    fmt.Print("\n")
    break
  case "DisableListCache":
    if flag.NArg() - 1 != 0 {
      fmt.Fprintln(os.Stderr, "DisableListCache requires 0 args")
      flag.Usage()
    }
    fmt.Print(client.DisableListCache(context.Background()))
    fmt.Print("\n")
    break
  case "EnableListCacheStats":
    if flag.NArg() - 1 != 0 {
      fmt.Fprintln(os.Stderr, "EnableListCacheStats requires 0 args")
      flag.Usage()
    }
    fmt.Print(client.EnableListCacheStats(context.Background()))
    fmt.Print("\n")
    break
  case "DisableListCacheStats":
    if flag.NArg() - 1 != 0 {
      fmt.Fprintln(os.Stderr, "DisableListCacheStats requires 0 args")
      flag.Usage()
    }
    fmt.Print(client.DisableListCacheStats(context.Background()))
    fmt.Print("\n")
    break
  case "FetchListCacheInfo":
    if flag.NArg() - 1 != 0 {
      fmt.Fprintln(os.Stderr, "FetchListCacheInfo requires 0 args")
      flag.Usage()
    }
    fmt.Print(client.FetchListCacheInfo(context.Background()))
    fmt.Print("\n")
    break
  case "GetCurrentFilesTotal":
    if flag.NArg() - 1 != 0 {
      fmt.Fprintln(os.Stderr, "GetCurrentFilesTotal requires 0 args")
      flag.Usage()
    }
    fmt.Print(client.GetCurrentFilesTotal(context.Background()))
    fmt.Print("\n")
    break
  case "GetFilesTotal":
    if flag.NArg() - 1 != 2 {
      fmt.Fprintln(os.Stderr, "GetFilesTotal requires 2 args")
      flag.Usage()
    }
    arg461 := flag.Arg(1)
    mbTrans462 := thrift.NewTMemoryBufferLen(len(arg461))
    defer mbTrans462.Close()
    _, err463 := mbTrans462.WriteString(arg461)
    if err463 != nil {
      Usage()
      return
    }
    factory464 := thrift.NewTJSONProtocolFactory()
    jsProt465 := factory464.GetProtocol(mbTrans462)
    argvalue0 := evfs.NewNcTEVFSDate()
    err466 := argvalue0.Read(context.Background(), jsProt465)
    if err466 != nil {
      Usage()
      return
    }
    value0 := argvalue0
    tmp1, err := (strconv.Atoi(flag.Arg(2)))
    if err != nil {
      Usage()
     return
    }
    argvalue1 := evfs.NcTEVFSDateUnit(tmp1)
    value1 := argvalue1
    fmt.Print(client.GetFilesTotal(context.Background(), value0, value1))
    fmt.Print("\n")
    break
  case "GetFilesChangeInfo":
    if flag.NArg() - 1 != 2 {
      fmt.Fprintln(os.Stderr, "GetFilesChangeInfo requires 2 args")
      flag.Usage()
    }
    arg467 := flag.Arg(1)
    mbTrans468 := thrift.NewTMemoryBufferLen(len(arg467))
    defer mbTrans468.Close()
    _, err469 := mbTrans468.WriteString(arg467)
    if err469 != nil {
      Usage()
      return
    }
    factory470 := thrift.NewTJSONProtocolFactory()
    jsProt471 := factory470.GetProtocol(mbTrans468)
    argvalue0 := evfs.NewNcTEVFSDate()
    err472 := argvalue0.Read(context.Background(), jsProt471)
    if err472 != nil {
      Usage()
      return
    }
    value0 := argvalue0
    tmp1, err := (strconv.Atoi(flag.Arg(2)))
    if err != nil {
      Usage()
     return
    }
    argvalue1 := evfs.NcTEVFSDateUnit(tmp1)
    value1 := argvalue1
    fmt.Print(client.GetFilesChangeInfo(context.Background(), value0, value1))
    fmt.Print("\n")
    break
  case "FetchSpaceQuotaInfo":
    if flag.NArg() - 1 != 1 {
      fmt.Fprintln(os.Stderr, "FetchSpaceQuotaInfo requires 1 args")
      flag.Usage()
    }
    argvalue0 := flag.Arg(1)
    value0 := argvalue0
    fmt.Print(client.FetchSpaceQuotaInfo(context.Background(), value0))
    fmt.Print("\n")
    break
  case "SetQuotaInfo":
    if flag.NArg() - 1 != 2 {
      fmt.Fprintln(os.Stderr, "SetQuotaInfo requires 2 args")
      flag.Usage()
    }
    argvalue0 := flag.Arg(1)
    value0 := argvalue0
    argvalue1, err475 := (strconv.ParseInt(flag.Arg(2), 10, 64))
    if err475 != nil {
      Usage()
      return
    }
    value1 := argvalue1
    fmt.Print(client.SetQuotaInfo(context.Background(), value0, value1))
    fmt.Print("\n")
    break
  case "FetchOperatedInfo":
    if flag.NArg() - 1 != 3 {
      fmt.Fprintln(os.Stderr, "FetchOperatedInfo requires 3 args")
      flag.Usage()
    }
    arg476 := flag.Arg(1)
    mbTrans477 := thrift.NewTMemoryBufferLen(len(arg476))
    defer mbTrans477.Close()
    _, err478 := mbTrans477.WriteString(arg476)
    if err478 != nil {
      Usage()
      return
    }
    factory479 := thrift.NewTJSONProtocolFactory()
    jsProt480 := factory479.GetProtocol(mbTrans477)
    argvalue0 := evfs.NewNcTEVFSDate()
    err481 := argvalue0.Read(context.Background(), jsProt480)
    if err481 != nil {
      Usage()
      return
    }
    value0 := argvalue0
    arg482 := flag.Arg(2)
    mbTrans483 := thrift.NewTMemoryBufferLen(len(arg482))
    defer mbTrans483.Close()
    _, err484 := mbTrans483.WriteString(arg482)
    if err484 != nil {
      Usage()
      return
    }
    factory485 := thrift.NewTJSONProtocolFactory()
    jsProt486 := factory485.GetProtocol(mbTrans483)
    argvalue1 := evfs.NewNcTEVFSDate()
    err487 := argvalue1.Read(context.Background(), jsProt486)
    if err487 != nil {
      Usage()
      return
    }
    value1 := argvalue1
    tmp2, err := (strconv.Atoi(flag.Arg(3)))
    if err != nil {
      Usage()
     return
    }
    argvalue2 := evfs.NcTEVFSOperatedType(tmp2)
    value2 := argvalue2
    fmt.Print(client.FetchOperatedInfo(context.Background(), value0, value1, value2))
    fmt.Print("\n")
    break
  case "FetchAllOperatedInfo":
    if flag.NArg() - 1 != 2 {
      fmt.Fprintln(os.Stderr, "FetchAllOperatedInfo requires 2 args")
      flag.Usage()
    }
    arg488 := flag.Arg(1)
    mbTrans489 := thrift.NewTMemoryBufferLen(len(arg488))
    defer mbTrans489.Close()
    _, err490 := mbTrans489.WriteString(arg488)
    if err490 != nil {
      Usage()
      return
    }
    factory491 := thrift.NewTJSONProtocolFactory()
    jsProt492 := factory491.GetProtocol(mbTrans489)
    argvalue0 := evfs.NewNcTEVFSDate()
    err493 := argvalue0.Read(context.Background(), jsProt492)
    if err493 != nil {
      Usage()
      return
    }
    value0 := argvalue0
    arg494 := flag.Arg(2)
    mbTrans495 := thrift.NewTMemoryBufferLen(len(arg494))
    defer mbTrans495.Close()
    _, err496 := mbTrans495.WriteString(arg494)
    if err496 != nil {
      Usage()
      return
    }
    factory497 := thrift.NewTJSONProtocolFactory()
    jsProt498 := factory497.GetProtocol(mbTrans495)
    argvalue1 := evfs.NewNcTEVFSDate()
    err499 := argvalue1.Read(context.Background(), jsProt498)
    if err499 != nil {
      Usage()
      return
    }
    value1 := argvalue1
    fmt.Print(client.FetchAllOperatedInfo(context.Background(), value0, value1))
    fmt.Print("\n")
    break
  case "GetRapidUploadSupport":
    if flag.NArg() - 1 != 0 {
      fmt.Fprintln(os.Stderr, "GetRapidUploadSupport requires 0 args")
      flag.Usage()
    }
    fmt.Print(client.GetRapidUploadSupport(context.Background()))
    fmt.Print("\n")
    break
  case "SetRapidUploadSupport":
    if flag.NArg() - 1 != 1 {
      fmt.Fprintln(os.Stderr, "SetRapidUploadSupport requires 1 args")
      flag.Usage()
    }
    argvalue0 := flag.Arg(1) == "true"
    value0 := argvalue0
    fmt.Print(client.SetRapidUploadSupport(context.Background(), value0))
    fmt.Print("\n")
    break
  case "GetCrossOSSRapidUploadStatus":
    if flag.NArg() - 1 != 0 {
      fmt.Fprintln(os.Stderr, "GetCrossOSSRapidUploadStatus requires 0 args")
      flag.Usage()
    }
    fmt.Print(client.GetCrossOSSRapidUploadStatus(context.Background()))
    fmt.Print("\n")
    break
  case "SetCrossOSSRapidUploadStatus":
    if flag.NArg() - 1 != 1 {
      fmt.Fprintln(os.Stderr, "SetCrossOSSRapidUploadStatus requires 1 args")
      flag.Usage()
    }
    argvalue0 := flag.Arg(1) == "true"
    value0 := argvalue0
    fmt.Print(client.SetCrossOSSRapidUploadStatus(context.Background(), value0))
    fmt.Print("\n")
    break
  case "FetchRapidStatisInfo":
    if flag.NArg() - 1 != 0 {
      fmt.Fprintln(os.Stderr, "FetchRapidStatisInfo requires 0 args")
      flag.Usage()
    }
    fmt.Print(client.FetchRapidStatisInfo(context.Background()))
    fmt.Print("\n")
    break
  case "FetchTotalRapidFile":
    if flag.NArg() - 1 != 5 {
      fmt.Fprintln(os.Stderr, "FetchTotalRapidFile requires 5 args")
      flag.Usage()
    }
    argvalue0 := flag.Arg(1)
    value0 := argvalue0
    argvalue1, err503 := (strconv.ParseInt(flag.Arg(2), 10, 64))
    if err503 != nil {
      Usage()
      return
    }
    value1 := argvalue1
    argvalue2, err504 := (strconv.ParseInt(flag.Arg(3), 10, 64))
    if err504 != nil {
      Usage()
      return
    }
    value2 := argvalue2
    argvalue3, err505 := (strconv.ParseInt(flag.Arg(4), 10, 64))
    if err505 != nil {
      Usage()
      return
    }
    value3 := argvalue3
    argvalue4, err506 := (strconv.ParseInt(flag.Arg(5), 10, 64))
    if err506 != nil {
      Usage()
      return
    }
    value4 := argvalue4
    fmt.Print(client.FetchTotalRapidFile(context.Background(), value0, value1, value2, value3, value4))
    fmt.Print("\n")
    break
  case "FetchRapidFilesInfo":
    if flag.NArg() - 1 != 7 {
      fmt.Fprintln(os.Stderr, "FetchRapidFilesInfo requires 7 args")
      flag.Usage()
    }
    argvalue0 := flag.Arg(1)
    value0 := argvalue0
    argvalue1, err508 := (strconv.ParseInt(flag.Arg(2), 10, 64))
    if err508 != nil {
      Usage()
      return
    }
    value1 := argvalue1
    argvalue2, err509 := (strconv.ParseInt(flag.Arg(3), 10, 64))
    if err509 != nil {
      Usage()
      return
    }
    value2 := argvalue2
    argvalue3, err510 := (strconv.ParseInt(flag.Arg(4), 10, 64))
    if err510 != nil {
      Usage()
      return
    }
    value3 := argvalue3
    argvalue4, err511 := (strconv.ParseInt(flag.Arg(5), 10, 64))
    if err511 != nil {
      Usage()
      return
    }
    value4 := argvalue4
    argvalue5, err512 := (strconv.ParseInt(flag.Arg(6), 10, 64))
    if err512 != nil {
      Usage()
      return
    }
    value5 := argvalue5
    tmp6, err513 := (strconv.Atoi(flag.Arg(7)))
    if err513 != nil {
      Usage()
      return
    }
    argvalue6 := int32(tmp6)
    value6 := argvalue6
    fmt.Print(client.FetchRapidFilesInfo(context.Background(), value0, value1, value2, value3, value4, value5, value6))
    fmt.Print("\n")
    break
  case "GetCSFLevel":
    if flag.NArg() - 1 != 1 {
      fmt.Fprintln(os.Stderr, "GetCSFLevel requires 1 args")
      flag.Usage()
    }
    argvalue0 := flag.Arg(1)
    value0 := argvalue0
    fmt.Print(client.GetCSFLevel(context.Background(), value0))
    fmt.Print("\n")
    break
  case "GetDirCSFLevel":
    if flag.NArg() - 1 != 1 {
      fmt.Fprintln(os.Stderr, "GetDirCSFLevel requires 1 args")
      flag.Usage()
    }
    argvalue0 := flag.Arg(1)
    value0 := argvalue0
    fmt.Print(client.GetDirCSFLevel(context.Background(), value0))
    fmt.Print("\n")
    break
  case "SetPreConvertEnable":
    if flag.NArg() - 1 != 1 {
      fmt.Fprintln(os.Stderr, "SetPreConvertEnable requires 1 args")
      flag.Usage()
    }
    argvalue0 := flag.Arg(1) == "true"
    value0 := argvalue0
    fmt.Print(client.SetPreConvertEnable(context.Background(), value0))
    fmt.Print("\n")
    break
  case "ObjMeta_AddAppInfo":
    if flag.NArg() - 1 != 2 {
      fmt.Fprintln(os.Stderr, "ObjMeta_AddAppInfo requires 2 args")
      flag.Usage()
    }
    argvalue0 := flag.Arg(1)
    value0 := argvalue0
    argvalue1 := flag.Arg(2)
    value1 := argvalue1
    fmt.Print(client.ObjMeta_AddAppInfo(context.Background(), value0, value1))
    fmt.Print("\n")
    break
  case "ObjMeta_GetAppInfos":
    if flag.NArg() - 1 != 0 {
      fmt.Fprintln(os.Stderr, "ObjMeta_GetAppInfos requires 0 args")
      flag.Usage()
    }
    fmt.Print(client.ObjMeta_GetAppInfos(context.Background()))
    fmt.Print("\n")
    break
  case "ObjMeta_SetAppName":
    if flag.NArg() - 1 != 2 {
      fmt.Fprintln(os.Stderr, "ObjMeta_SetAppName requires 2 args")
      flag.Usage()
    }
    argvalue0 := flag.Arg(1)
    value0 := argvalue0
    argvalue1 := flag.Arg(2)
    value1 := argvalue1
    fmt.Print(client.ObjMeta_SetAppName(context.Background(), value0, value1))
    fmt.Print("\n")
    break
  case "ObjMeta_SetAppStatus":
    if flag.NArg() - 1 != 2 {
      fmt.Fprintln(os.Stderr, "ObjMeta_SetAppStatus requires 2 args")
      flag.Usage()
    }
    argvalue0 := flag.Arg(1)
    value0 := argvalue0
    tmp1, err522 := (strconv.Atoi(flag.Arg(2)))
    if err522 != nil {
      Usage()
      return
    }
    argvalue1 := int32(tmp1)
    value1 := argvalue1
    fmt.Print(client.ObjMeta_SetAppStatus(context.Background(), value0, value1))
    fmt.Print("\n")
    break
  case "ObjMeta_DeleteAppInfo":
    if flag.NArg() - 1 != 1 {
      fmt.Fprintln(os.Stderr, "ObjMeta_DeleteAppInfo requires 1 args")
      flag.Usage()
    }
    argvalue0 := flag.Arg(1)
    value0 := argvalue0
    fmt.Print(client.ObjMeta_DeleteAppInfo(context.Background(), value0))
    fmt.Print("\n")
    break
  case "SetUserDownloadLimitStatus":
    if flag.NArg() - 1 != 1 {
      fmt.Fprintln(os.Stderr, "SetUserDownloadLimitStatus requires 1 args")
      flag.Usage()
    }
    argvalue0 := flag.Arg(1) == "true"
    value0 := argvalue0
    fmt.Print(client.SetUserDownloadLimitStatus(context.Background(), value0))
    fmt.Print("\n")
    break
  case "GetUserDonwloadLimitStatus":
    if flag.NArg() - 1 != 0 {
      fmt.Fprintln(os.Stderr, "GetUserDonwloadLimitStatus requires 0 args")
      flag.Usage()
    }
    fmt.Print(client.GetUserDonwloadLimitStatus(context.Background()))
    fmt.Print("\n")
    break
  case "AddUserDownloadLimitInfos":
    if flag.NArg() - 1 != 1 {
      fmt.Fprintln(os.Stderr, "AddUserDownloadLimitInfos requires 1 args")
      flag.Usage()
    }
    arg525 := flag.Arg(1)
    mbTrans526 := thrift.NewTMemoryBufferLen(len(arg525))
    defer mbTrans526.Close()
    _, err527 := mbTrans526.WriteString(arg525)
    if err527 != nil { 
      Usage()
      return
    }
    factory528 := thrift.NewTJSONProtocolFactory()
    jsProt529 := factory528.GetProtocol(mbTrans526)
    containerStruct0 := evfs.NewNcTEVFSAddUserDownloadLimitInfosArgs()
    err530 := containerStruct0.ReadField1(context.Background(), jsProt529)
    if err530 != nil {
      Usage()
      return
    }
    argvalue0 := containerStruct0.LimitInfos
    value0 := argvalue0
    fmt.Print(client.AddUserDownloadLimitInfos(context.Background(), value0))
    fmt.Print("\n")
    break
  case "GetUserDownloadLimitInfos":
    if flag.NArg() - 1 != 0 {
      fmt.Fprintln(os.Stderr, "GetUserDownloadLimitInfos requires 0 args")
      flag.Usage()
    }
    fmt.Print(client.GetUserDownloadLimitInfos(context.Background()))
    fmt.Print("\n")
    break
  case "DeleteUserDownloadLimitInfos":
    if flag.NArg() - 1 != 1 {
      fmt.Fprintln(os.Stderr, "DeleteUserDownloadLimitInfos requires 1 args")
      flag.Usage()
    }
    arg531 := flag.Arg(1)
    mbTrans532 := thrift.NewTMemoryBufferLen(len(arg531))
    defer mbTrans532.Close()
    _, err533 := mbTrans532.WriteString(arg531)
    if err533 != nil { 
      Usage()
      return
    }
    factory534 := thrift.NewTJSONProtocolFactory()
    jsProt535 := factory534.GetProtocol(mbTrans532)
    containerStruct0 := evfs.NewNcTEVFSDeleteUserDownloadLimitInfosArgs()
    err536 := containerStruct0.ReadField1(context.Background(), jsProt535)
    if err536 != nil {
      Usage()
      return
    }
    argvalue0 := containerStruct0.UserIds
    value0 := argvalue0
    fmt.Print(client.DeleteUserDownloadLimitInfos(context.Background(), value0))
    fmt.Print("\n")
    break
  case "GetQuarantineFileList":
    if flag.NArg() - 1 != 3 {
      fmt.Fprintln(os.Stderr, "GetQuarantineFileList requires 3 args")
      flag.Usage()
    }
    arg537 := flag.Arg(1)
    mbTrans538 := thrift.NewTMemoryBufferLen(len(arg537))
    defer mbTrans538.Close()
    _, err539 := mbTrans538.WriteString(arg537)
    if err539 != nil {
      Usage()
      return
    }
    factory540 := thrift.NewTJSONProtocolFactory()
    jsProt541 := factory540.GetProtocol(mbTrans538)
    argvalue0 := evfs.NewNcTFiltrationParam()
    err542 := argvalue0.Read(context.Background(), jsProt541)
    if err542 != nil {
      Usage()
      return
    }
    value0 := argvalue0
    argvalue1, err543 := (strconv.ParseInt(flag.Arg(2), 10, 64))
    if err543 != nil {
      Usage()
      return
    }
    value1 := argvalue1
    argvalue2, err544 := (strconv.ParseInt(flag.Arg(3), 10, 64))
    if err544 != nil {
      Usage()
      return
    }
    value2 := argvalue2
    fmt.Print(client.GetQuarantineFileList(context.Background(), value0, value1, value2))
    fmt.Print("\n")
    break
  case "GetFileVersionList":
    if flag.NArg() - 1 != 2 {
      fmt.Fprintln(os.Stderr, "GetFileVersionList requires 2 args")
      flag.Usage()
    }
    argvalue0 := flag.Arg(1)
    value0 := argvalue0
    argvalue1 := flag.Arg(2)
    value1 := argvalue1
    fmt.Print(client.GetFileVersionList(context.Background(), value0, value1))
    fmt.Print("\n")
    break
  case "GetQuarantineFileCount":
    if flag.NArg() - 1 != 1 {
      fmt.Fprintln(os.Stderr, "GetQuarantineFileCount requires 1 args")
      flag.Usage()
    }
    arg547 := flag.Arg(1)
    mbTrans548 := thrift.NewTMemoryBufferLen(len(arg547))
    defer mbTrans548.Close()
    _, err549 := mbTrans548.WriteString(arg547)
    if err549 != nil {
      Usage()
      return
    }
    factory550 := thrift.NewTJSONProtocolFactory()
    jsProt551 := factory550.GetProtocol(mbTrans548)
    argvalue0 := evfs.NewNcTFiltrationParam()
    err552 := argvalue0.Read(context.Background(), jsProt551)
    if err552 != nil {
      Usage()
      return
    }
    value0 := argvalue0
    fmt.Print(client.GetQuarantineFileCount(context.Background(), value0))
    fmt.Print("\n")
    break
  case "OSDownload":
    if flag.NArg() - 1 != 6 {
      fmt.Fprintln(os.Stderr, "OSDownload requires 6 args")
      flag.Usage()
    }
    argvalue0 := flag.Arg(1)
    value0 := argvalue0
    argvalue1 := flag.Arg(2)
    value1 := argvalue1
    argvalue2 := flag.Arg(3)
    value2 := argvalue2
    argvalue3 := flag.Arg(4)
    value3 := argvalue3
    argvalue4 := flag.Arg(5) == "true"
    value4 := argvalue4
    argvalue5 := flag.Arg(6)
    value5 := argvalue5
    fmt.Print(client.OSDownload(context.Background(), value0, value1, value2, value3, value4, value5))
    fmt.Print("\n")
    break
  case "RestoreQuarantineFile":
    if flag.NArg() - 1 != 2 {
      fmt.Fprintln(os.Stderr, "RestoreQuarantineFile requires 2 args")
      flag.Usage()
    }
    argvalue0 := flag.Arg(1)
    value0 := argvalue0
    tmp1, err560 := (strconv.Atoi(flag.Arg(2)))
    if err560 != nil {
      Usage()
      return
    }
    argvalue1 := int32(tmp1)
    value1 := argvalue1
    fmt.Print(client.RestoreQuarantineFile(context.Background(), value0, value1))
    fmt.Print("\n")
    break
  case "DeleteQuarantineFile":
    if flag.NArg() - 1 != 1 {
      fmt.Fprintln(os.Stderr, "DeleteQuarantineFile requires 1 args")
      flag.Usage()
    }
    argvalue0 := flag.Arg(1)
    value0 := argvalue0
    fmt.Print(client.DeleteQuarantineFile(context.Background(), value0))
    fmt.Print("\n")
    break
  case "Quarantine":
    if flag.NArg() - 1 != 3 {
      fmt.Fprintln(os.Stderr, "Quarantine requires 3 args")
      flag.Usage()
    }
    argvalue0 := flag.Arg(1)
    value0 := argvalue0
    argvalue1 := flag.Arg(2)
    value1 := argvalue1
    tmp2, err := (strconv.Atoi(flag.Arg(3)))
    if err != nil {
      Usage()
     return
    }
    argvalue2 := evfs.NcTEVFSQuarantineType(tmp2)
    value2 := argvalue2
    fmt.Print(client.Quarantine(context.Background(), value0, value1, value2))
    fmt.Print("\n")
    break
  case "QRT_GetConfig":
    if flag.NArg() - 1 != 0 {
      fmt.Fprintln(os.Stderr, "QRT_GetConfig requires 0 args")
      flag.Usage()
    }
    fmt.Print(client.QRT_GetConfig(context.Background()))
    fmt.Print("\n")
    break
  case "QRT_SetAppealProtectTime":
    if flag.NArg() - 1 != 1 {
      fmt.Fprintln(os.Stderr, "QRT_SetAppealProtectTime requires 1 args")
      flag.Usage()
    }
    tmp0, err564 := (strconv.Atoi(flag.Arg(1)))
    if err564 != nil {
      Usage()
      return
    }
    argvalue0 := int32(tmp0)
    value0 := argvalue0
    fmt.Print(client.QRT_SetAppealProtectTime(context.Background(), value0))
    fmt.Print("\n")
    break
  case "QRT_SetAutoDeleteTime":
    if flag.NArg() - 1 != 1 {
      fmt.Fprintln(os.Stderr, "QRT_SetAutoDeleteTime requires 1 args")
      flag.Usage()
    }
    tmp0, err565 := (strconv.Atoi(flag.Arg(1)))
    if err565 != nil {
      Usage()
      return
    }
    argvalue0 := int32(tmp0)
    value0 := argvalue0
    fmt.Print(client.QRT_SetAutoDeleteTime(context.Background(), value0))
    fmt.Print("\n")
    break
  case "QRT_AppealApproval":
    if flag.NArg() - 1 != 4 {
      fmt.Fprintln(os.Stderr, "QRT_AppealApproval requires 4 args")
      flag.Usage()
    }
    argvalue0 := flag.Arg(1)
    value0 := argvalue0
    argvalue1 := flag.Arg(2) == "true"
    value1 := argvalue1
    tmp2, err568 := (strconv.Atoi(flag.Arg(3)))
    if err568 != nil {
      Usage()
      return
    }
    argvalue2 := int32(tmp2)
    value2 := argvalue2
    argvalue3 := flag.Arg(4)
    value3 := argvalue3
    fmt.Print(client.QRT_AppealApproval(context.Background(), value0, value1, value2, value3))
    fmt.Print("\n")
    break
  case "GetFileInfoCount":
    if flag.NArg() - 1 != 1 {
      fmt.Fprintln(os.Stderr, "GetFileInfoCount requires 1 args")
      flag.Usage()
    }
    argvalue0 := flag.Arg(1)
    value0 := argvalue0
    fmt.Print(client.GetFileInfoCount(context.Background(), value0))
    fmt.Print("\n")
    break
  case "GetPageFileInfo":
    if flag.NArg() - 1 != 1 {
      fmt.Fprintln(os.Stderr, "GetPageFileInfo requires 1 args")
      flag.Usage()
    }
    arg571 := flag.Arg(1)
    mbTrans572 := thrift.NewTMemoryBufferLen(len(arg571))
    defer mbTrans572.Close()
    _, err573 := mbTrans572.WriteString(arg571)
    if err573 != nil {
      Usage()
      return
    }
    factory574 := thrift.NewTJSONProtocolFactory()
    jsProt575 := factory574.GetProtocol(mbTrans572)
    argvalue0 := evfs.NewNcTEVFSGetPageFileInfoParam()
    err576 := argvalue0.Read(context.Background(), jsProt575)
    if err576 != nil {
      Usage()
      return
    }
    value0 := argvalue0
    fmt.Print(client.GetPageFileInfo(context.Background(), value0))
    fmt.Print("\n")
    break
  case "GetFileRevisions":
    if flag.NArg() - 1 != 1 {
      fmt.Fprintln(os.Stderr, "GetFileRevisions requires 1 args")
      flag.Usage()
    }
    argvalue0 := flag.Arg(1)
    value0 := argvalue0
    fmt.Print(client.GetFileRevisions(context.Background(), value0))
    fmt.Print("\n")
    break
  case "GetDocDueRemindStatus":
    if flag.NArg() - 1 != 0 {
      fmt.Fprintln(os.Stderr, "GetDocDueRemindStatus requires 0 args")
      flag.Usage()
    }
    fmt.Print(client.GetDocDueRemindStatus(context.Background()))
    fmt.Print("\n")
    break
  case "SetDocDueRemindStatus":
    if flag.NArg() - 1 != 1 {
      fmt.Fprintln(os.Stderr, "SetDocDueRemindStatus requires 1 args")
      flag.Usage()
    }
    argvalue0 := flag.Arg(1) == "true"
    value0 := argvalue0
    fmt.Print(client.SetDocDueRemindStatus(context.Background(), value0))
    fmt.Print("\n")
    break
  case "GetDocDueRemindMsgSendTime":
    if flag.NArg() - 1 != 0 {
      fmt.Fprintln(os.Stderr, "GetDocDueRemindMsgSendTime requires 0 args")
      flag.Usage()
    }
    fmt.Print(client.GetDocDueRemindMsgSendTime(context.Background()))
    fmt.Print("\n")
    break
  case "SetDocDueRemindMsgSendTime":
    if flag.NArg() - 1 != 1 {
      fmt.Fprintln(os.Stderr, "SetDocDueRemindMsgSendTime requires 1 args")
      flag.Usage()
    }
    tmp0, err579 := (strconv.Atoi(flag.Arg(1)))
    if err579 != nil {
      Usage()
      return
    }
    argvalue0 := int32(tmp0)
    value0 := argvalue0
    fmt.Print(client.SetDocDueRemindMsgSendTime(context.Background(), value0))
    fmt.Print("\n")
    break
  case "SetNSQPubEnableStatus":
    if flag.NArg() - 1 != 1 {
      fmt.Fprintln(os.Stderr, "SetNSQPubEnableStatus requires 1 args")
      flag.Usage()
    }
    argvalue0 := flag.Arg(1) == "true"
    value0 := argvalue0
    fmt.Print(client.SetNSQPubEnableStatus(context.Background(), value0))
    fmt.Print("\n")
    break
  case "GetNSQPubEnableStatus":
    if flag.NArg() - 1 != 0 {
      fmt.Fprintln(os.Stderr, "GetNSQPubEnableStatus requires 0 args")
      flag.Usage()
    }
    fmt.Print(client.GetNSQPubEnableStatus(context.Background()))
    fmt.Print("\n")
    break
  case "EVFS_ThriftServerPing":
    if flag.NArg() - 1 != 0 {
      fmt.Fprintln(os.Stderr, "EVFS_ThriftServerPing requires 0 args")
      flag.Usage()
    }
    fmt.Print(client.EVFS_ThriftServerPing(context.Background()))
    fmt.Print("\n")
    break
  case "":
    Usage()
    break
  default:
    fmt.Fprintln(os.Stderr, "Invalid function ", cmd)
  }
}
