// Code generated by MockGen. DO NOT EDIT.
// Source: ./document.go
//
// Generated by this command:
//
//	mockgen -source=./document.go -destination ./httpaccmock/document_mock.go -package httpaccmock
//

// Package httpaccmock is a generated GoMock package.
package httpaccmock

import (
	docaccret "AuditLog/drivenadapters/httpaccess/document/docaccret"
	reflect "reflect"

	gomock "go.uber.org/mock/gomock"
)

// MockDocumentHttpAcc is a mock of DocumentHttpAcc interface.
type MockDocumentHttpAcc struct {
	ctrl     *gomock.Controller
	recorder *MockDocumentHttpAccMockRecorder
	isgomock struct{}
}

// MockDocumentHttpAccMockRecorder is the mock recorder for MockDocumentHttpAcc.
type MockDocumentHttpAccMockRecorder struct {
	mock *MockDocumentHttpAcc
}

// NewMockDocumentHttpAcc creates a new mock instance.
func NewMockDocumentHttpAcc(ctrl *gomock.Controller) *MockDocumentHttpAcc {
	mock := &MockDocumentHttpAcc{ctrl: ctrl}
	mock.recorder = &MockDocumentHttpAccMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockDocumentHttpAcc) EXPECT() *MockDocumentHttpAccMockRecorder {
	return m.recorder
}

// GetBatchDocLibInfos mocks base method.
func (m *MockDocumentHttpAcc) GetBatchDocLibInfos(docIDs []string) ([]*docaccret.DocLibItem, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetBatchDocLibInfos", docIDs)
	ret0, _ := ret[0].([]*docaccret.DocLibItem)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetBatchDocLibInfos indicates an expected call of GetBatchDocLibInfos.
func (mr *MockDocumentHttpAccMockRecorder) GetBatchDocLibInfos(docIDs any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetBatchDocLibInfos", reflect.TypeOf((*MockDocumentHttpAcc)(nil).GetBatchDocLibInfos), docIDs)
}
