// Code generated by MockGen. DO NOT EDIT.
// Source: ./efast.go
//
// Generated by this command:
//
//	mockgen -source=./efast.go -destination ./httpaccmock/efast_mock.go -package httpaccmock
//

// Package httpaccmock is a generated GoMock package.
package httpaccmock

import (
	enums "AuditLog/common/enums"
	context "context"
	reflect "reflect"

	gomock "go.uber.org/mock/gomock"
)

// MockEFastHttpAcc is a mock of EFastHttpAcc interface.
type MockEFastHttpAcc struct {
	ctrl     *gomock.Controller
	recorder *MockEFastHttpAccMockRecorder
	isgomock struct{}
}

// MockEFastHttpAccMockRecorder is the mock recorder for MockEFastHttpAcc.
type MockEFastHttpAccMockRecorder struct {
	mock *MockEFastHttpAcc
}

// NewMockEFastHttpAcc creates a new mock instance.
func NewMockEFastHttpAcc(ctrl *gomock.Controller) *MockEFastHttpAcc {
	mock := &MockEFastHttpAcc{ctrl: ctrl}
	mock.recorder = &MockEFastHttpAccMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockEFastHttpAcc) EXPECT() *MockEFastHttpAccMockRecorder {
	return m.recorder
}

// CheckObjExists mocks base method.
func (m *MockEFastHttpAcc) CheckObjExists(ctx context.Context, ids []string) ([]string, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CheckObjExists", ctx, ids)
	ret0, _ := ret[0].([]string)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CheckObjExists indicates an expected call of CheckObjExists.
func (mr *MockEFastHttpAccMockRecorder) CheckObjExists(ctx, ids any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CheckObjExists", reflect.TypeOf((*MockEFastHttpAcc)(nil).CheckObjExists), ctx, ids)
}

// CheckOneObjExists mocks base method.
func (m *MockEFastHttpAcc) CheckOneObjExists(ctx context.Context, id string) (bool, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CheckOneObjExists", ctx, id)
	ret0, _ := ret[0].(bool)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CheckOneObjExists indicates an expected call of CheckOneObjExists.
func (mr *MockEFastHttpAccMockRecorder) CheckOneObjExists(ctx, id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CheckOneObjExists", reflect.TypeOf((*MockEFastHttpAcc)(nil).CheckOneObjExists), ctx, id)
}

// CreateMultiLevelDir mocks base method.
func (m *MockEFastHttpAcc) CreateMultiLevelDir(ctx context.Context, parentDocID, path, token string) (string, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateMultiLevelDir", ctx, parentDocID, path, token)
	ret0, _ := ret[0].(string)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CreateMultiLevelDir indicates an expected call of CreateMultiLevelDir.
func (mr *MockEFastHttpAccMockRecorder) CreateMultiLevelDir(ctx, parentDocID, path, token any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateMultiLevelDir", reflect.TypeOf((*MockEFastHttpAcc)(nil).CreateMultiLevelDir), ctx, parentDocID, path, token)
}

// GetDocLibType mocks base method.
func (m *MockEFastHttpAcc) GetDocLibType(ctx context.Context, gns string) (enums.DocLibType, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetDocLibType", ctx, gns)
	ret0, _ := ret[0].(enums.DocLibType)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetDocLibType indicates an expected call of GetDocLibType.
func (mr *MockEFastHttpAccMockRecorder) GetDocLibType(ctx, gns any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetDocLibType", reflect.TypeOf((*MockEFastHttpAcc)(nil).GetDocLibType), ctx, gns)
}

// GetOneFsName mocks base method.
func (m *MockEFastHttpAcc) GetOneFsName(ctx context.Context, docID string) (string, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetOneFsName", ctx, docID)
	ret0, _ := ret[0].(string)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetOneFsName indicates an expected call of GetOneFsName.
func (mr *MockEFastHttpAccMockRecorder) GetOneFsName(ctx, docID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetOneFsName", reflect.TypeOf((*MockEFastHttpAcc)(nil).GetOneFsName), ctx, docID)
}

// Gns2Path mocks base method.
func (m *MockEFastHttpAcc) Gns2Path(ctx context.Context, gns []string) (map[string]string, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Gns2Path", ctx, gns)
	ret0, _ := ret[0].(map[string]string)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Gns2Path indicates an expected call of Gns2Path.
func (mr *MockEFastHttpAccMockRecorder) Gns2Path(ctx, gns any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Gns2Path", reflect.TypeOf((*MockEFastHttpAcc)(nil).Gns2Path), ctx, gns)
}

// Path2Gns mocks base method.
func (m *MockEFastHttpAcc) Path2Gns(ctx context.Context, path, asToken string) (bool, string, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Path2Gns", ctx, path, asToken)
	ret0, _ := ret[0].(bool)
	ret1, _ := ret[1].(string)
	ret2, _ := ret[2].(error)
	return ret0, ret1, ret2
}

// Path2Gns indicates an expected call of Path2Gns.
func (mr *MockEFastHttpAccMockRecorder) Path2Gns(ctx, path, asToken any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Path2Gns", reflect.TypeOf((*MockEFastHttpAcc)(nil).Path2Gns), ctx, path, asToken)
}
