// Code generated by MockGen. DO NOT EDIT.
// Source: ./open_search.go
//
// Generated by this command:
//
//	mockgen -source=./open_search.go -destination ./httpaccmock/open_search_mock.go -package httpaccmock
//

// Package httpaccmock is a generated GoMock package.
package httpaccmock

import (
	context "context"
	reflect "reflect"

	gomock "go.uber.org/mock/gomock"
)

// MockOpsHttpAcc is a mock of OpsHttpAcc interface.
type MockOpsHttpAcc struct {
	ctrl     *gomock.Controller
	recorder *MockOpsHttpAccMockRecorder
	isgomock struct{}
}

// MockOpsHttpAccMockRecorder is the mock recorder for MockOpsHttpAcc.
type MockOpsHttpAccMockRecorder struct {
	mock *MockOpsHttpAcc
}

// NewMockOpsHttpAcc creates a new mock instance.
func NewMockOpsHttpAcc(ctrl *gomock.Controller) *MockOpsHttpAcc {
	mock := &MockOpsHttpAcc{ctrl: ctrl}
	mock.recorder = &MockOpsHttpAccMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockOpsHttpAcc) EXPECT() *MockOpsHttpAccMockRecorder {
	return m.recorder
}

// BatchCreate mocks base method.
func (m *MockOpsHttpAcc) BatchCreate(ctx context.Context, index string, data []map[string]any, isWithID bool) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "BatchCreate", ctx, index, data, isWithID)
	ret0, _ := ret[0].(error)
	return ret0
}

// BatchCreate indicates an expected call of BatchCreate.
func (mr *MockOpsHttpAccMockRecorder) BatchCreate(ctx, index, data, isWithID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "BatchCreate", reflect.TypeOf((*MockOpsHttpAcc)(nil).BatchCreate), ctx, index, data, isWithID)
}

// BatchCreateInterface mocks base method.
func (m *MockOpsHttpAcc) BatchCreateInterface(ctx context.Context, index string, docs any, isWithID bool) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "BatchCreateInterface", ctx, index, docs, isWithID)
	ret0, _ := ret[0].(error)
	return ret0
}

// BatchCreateInterface indicates an expected call of BatchCreateInterface.
func (mr *MockOpsHttpAccMockRecorder) BatchCreateInterface(ctx, index, docs, isWithID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "BatchCreateInterface", reflect.TypeOf((*MockOpsHttpAcc)(nil).BatchCreateInterface), ctx, index, docs, isWithID)
}

// CreateIndex mocks base method.
func (m *MockOpsHttpAcc) CreateIndex(ctx context.Context, index, mapping, setting string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateIndex", ctx, index, mapping, setting)
	ret0, _ := ret[0].(error)
	return ret0
}

// CreateIndex indicates an expected call of CreateIndex.
func (mr *MockOpsHttpAccMockRecorder) CreateIndex(ctx, index, mapping, setting any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateIndex", reflect.TypeOf((*MockOpsHttpAcc)(nil).CreateIndex), ctx, index, mapping, setting)
}

// CreateInterfaceNoID mocks base method.
func (m *MockOpsHttpAcc) CreateInterfaceNoID(ctx context.Context, index string, doc any) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateInterfaceNoID", ctx, index, doc)
	ret0, _ := ret[0].(error)
	return ret0
}

// CreateInterfaceNoID indicates an expected call of CreateInterfaceNoID.
func (mr *MockOpsHttpAccMockRecorder) CreateInterfaceNoID(ctx, index, doc any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateInterfaceNoID", reflect.TypeOf((*MockOpsHttpAcc)(nil).CreateInterfaceNoID), ctx, index, doc)
}

// DeleteDocByField mocks base method.
func (m *MockOpsHttpAcc) DeleteDocByField(ctx context.Context, index, field string, value any) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeleteDocByField", ctx, index, field, value)
	ret0, _ := ret[0].(error)
	return ret0
}

// DeleteDocByField indicates an expected call of DeleteDocByField.
func (mr *MockOpsHttpAccMockRecorder) DeleteDocByField(ctx, index, field, value any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteDocByField", reflect.TypeOf((*MockOpsHttpAcc)(nil).DeleteDocByField), ctx, index, field, value)
}

// DeleteDocsByFieldRange mocks base method.
func (m *MockOpsHttpAcc) DeleteDocsByFieldRange(ctx context.Context, index, field string, from, to any) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeleteDocsByFieldRange", ctx, index, field, from, to)
	ret0, _ := ret[0].(error)
	return ret0
}

// DeleteDocsByFieldRange indicates an expected call of DeleteDocsByFieldRange.
func (mr *MockOpsHttpAccMockRecorder) DeleteDocsByFieldRange(ctx, index, field, from, to any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteDocsByFieldRange", reflect.TypeOf((*MockOpsHttpAcc)(nil).DeleteDocsByFieldRange), ctx, index, field, from, to)
}

// DeleteIndex mocks base method.
func (m *MockOpsHttpAcc) DeleteIndex(ctx context.Context, index string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeleteIndex", ctx, index)
	ret0, _ := ret[0].(error)
	return ret0
}

// DeleteIndex indicates an expected call of DeleteIndex.
func (mr *MockOpsHttpAccMockRecorder) DeleteIndex(ctx, index any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteIndex", reflect.TypeOf((*MockOpsHttpAcc)(nil).DeleteIndex), ctx, index)
}
