// Code generated by MockGen. DO NOT EDIT.
// Source: svc_config.go
//
// Generated by this command:
//
//	mockgen -package persrecdbmock -source svc_config.go -destination ./persrecdbmock/svc_config.go
//

// Package persrecdbmock is a generated GoMock package.
package persrecdbmock

import (
	context "context"
	reflect "reflect"

	gomock "go.uber.org/mock/gomock"
)

// MockIPersSvcConfigRepo is a mock of IPersSvcConfigRepo interface.
type MockIPersSvcConfigRepo struct {
	ctrl     *gomock.Controller
	recorder *MockIPersSvcConfigRepoMockRecorder
	isgomock struct{}
}

// MockIPersSvcConfigRepoMockRecorder is the mock recorder for MockIPersSvcConfigRepo.
type MockIPersSvcConfigRepoMockRecorder struct {
	mock *MockIPersSvcConfigRepo
}

// NewMockIPersSvcConfigRepo creates a new mock instance.
func NewMockIPersSvcConfigRepo(ctrl *gomock.Controller) *MockIPersSvcConfigRepo {
	mock := &MockIPersSvcConfigRepo{ctrl: ctrl}
	mock.recorder = &MockIPersSvcConfigRepoMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockIPersSvcConfigRepo) EXPECT() *MockIPersSvcConfigRepoMockRecorder {
	return m.recorder
}

// Get mocks base method.
func (m *MockIPersSvcConfigRepo) Get(ctx context.Context, key string) (string, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Get", ctx, key)
	ret0, _ := ret[0].(string)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Get indicates an expected call of Get.
func (mr *MockIPersSvcConfigRepoMockRecorder) Get(ctx, key any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Get", reflect.TypeOf((*MockIPersSvcConfigRepo)(nil).Get), ctx, key)
}

// Set mocks base method.
func (m *MockIPersSvcConfigRepo) Set(ctx context.Context, key, val string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Set", ctx, key, val)
	ret0, _ := ret[0].(error)
	return ret0
}

// Set indicates an expected call of Set.
func (mr *MockIPersSvcConfigRepoMockRecorder) Set(ctx, key, val any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Set", reflect.TypeOf((*MockIPersSvcConfigRepo)(nil).Set), ctx, key, val)
}
