// Code generated by MockGen. DO NOT EDIT.
// Source: ./network/network.go

// Package mock_network is a generated GoMock package.
package mock_network

import (
	reflect "reflect"

	models "policy_mgnt/utils/models"

	gomock "go.uber.org/mock/gomock"

	api "policy_mgnt/utils/gocommon/api"
)

// MockManagement is a mock of Management interface.
type MockManagement struct {
	ctrl     *gomock.Controller
	recorder *MockManagementMockRecorder
}

// MockManagementMockRecorder is the mock recorder for MockManagement.
type MockManagementMockRecorder struct {
	mock *MockManagement
}

// NewMockManagement creates a new mock instance.
func NewMockManagement(ctrl *gomock.Controller) *MockManagement {
	mock := &MockManagement{ctrl: ctrl}
	mock.recorder = &MockManagementMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockManagement) EXPECT() *MockManagementMockRecorder {
	return m.recorder
}

// AddAccessors mocks base method.
func (m *MockManagement) AddAccessors(arg0 string, arg1 []models.AccessorInfo) []*api.MultiStatus {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "AddAccessors", arg0, arg1)
	ret0, _ := ret[0].([]*api.MultiStatus)
	return ret0
}

// AddAccessors indicates an expected call of AddAccessors.
func (mr *MockManagementMockRecorder) AddAccessors(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "AddAccessors", reflect.TypeOf((*MockManagement)(nil).AddAccessors), arg0, arg1)
}

// AddNetwork mocks base method.
func (m *MockManagement) AddNetwork(arg0 *models.NetworkRestriction) (string, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "AddNetwork", arg0)
	ret0, _ := ret[0].(string)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// AddNetwork indicates an expected call of AddNetwork.
func (mr *MockManagementMockRecorder) AddNetwork(arg0 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "AddNetwork", reflect.TypeOf((*MockManagement)(nil).AddNetwork), arg0)
}

// DeleteAccessors mocks base method.
func (m *MockManagement) DeleteAccessors(arg0 string, arg1 []string) []*api.MultiStatus {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeleteAccessors", arg0, arg1)
	ret0, _ := ret[0].([]*api.MultiStatus)
	return ret0
}

// DeleteAccessors indicates an expected call of DeleteAccessors.
func (mr *MockManagementMockRecorder) DeleteAccessors(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteAccessors", reflect.TypeOf((*MockManagement)(nil).DeleteAccessors), arg0, arg1)
}

// DeleteNetwork mocks base method.
func (m *MockManagement) DeleteNetwork(arg0 string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeleteNetwork", arg0)
	ret0, _ := ret[0].(error)
	return ret0
}

// DeleteNetwork indicates an expected call of DeleteNetwork.
func (mr *MockManagementMockRecorder) DeleteNetwork(arg0 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteNetwork", reflect.TypeOf((*MockManagement)(nil).DeleteNetwork), arg0)
}

// EditNetwork mocks base method.
func (m *MockManagement) EditNetwork(arg0 string, arg1 *models.NetworkRestriction) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "EditNetwork", arg0, arg1)
	ret0, _ := ret[0].(error)
	return ret0
}

// EditNetwork indicates an expected call of EditNetwork.
func (mr *MockManagementMockRecorder) EditNetwork(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "EditNetwork", reflect.TypeOf((*MockManagement)(nil).EditNetwork), arg0, arg1)
}

// FlushAccessors mocks base method.
func (m *MockManagement) FlushAccessors(arg0 []string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "FlushAccessors", arg0)
	ret0, _ := ret[0].(error)
	return ret0
}

// FlushAccessors indicates an expected call of FlushAccessors.
func (mr *MockManagementMockRecorder) FlushAccessors(arg0 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "FlushAccessors", reflect.TypeOf((*MockManagement)(nil).FlushAccessors), arg0)
}

// GetNetworkByID mocks base method.
func (m *MockManagement) GetNetworkByID(arg0 string) (models.WebNetworkRestriction, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetNetworkByID", arg0)
	ret0, _ := ret[0].(models.WebNetworkRestriction)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetNetworkByID indicates an expected call of GetNetworkByID.
func (mr *MockManagementMockRecorder) GetNetworkByID(arg0 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetNetworkByID", reflect.TypeOf((*MockManagement)(nil).GetNetworkByID), arg0)
}

// GetNetworkData mocks base method.
func (m *MockManagement) GetNetworkData(arg0 map[string]interface{}) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetNetworkData", arg0)
	ret0, _ := ret[0].(error)
	return ret0
}

// GetNetworkData indicates an expected call of GetNetworkData.
func (mr *MockManagementMockRecorder) GetNetworkData(arg0 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetNetworkData", reflect.TypeOf((*MockManagement)(nil).GetNetworkData), arg0)
}

// GetNetworksByAccessorID mocks base method.
func (m *MockManagement) GetNetworksByAccessorID(arg0 string, arg1, arg2 int) ([]models.WebNetworkRestriction, int, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetNetworksByAccessorID", arg0, arg1, arg2)
	ret0, _ := ret[0].([]models.WebNetworkRestriction)
	ret1, _ := ret[1].(int)
	ret2, _ := ret[2].(error)
	return ret0, ret1, ret2
}

// GetNetworksByAccessorID indicates an expected call of GetNetworksByAccessorID.
func (mr *MockManagementMockRecorder) GetNetworksByAccessorID(arg0, arg1, arg2 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetNetworksByAccessorID", reflect.TypeOf((*MockManagement)(nil).GetNetworksByAccessorID), arg0, arg1, arg2)
}

// SearchAccessors mocks base method.
func (m *MockManagement) SearchAccessors(arg0, arg1 string, arg2, arg3 int) ([]models.AccessorInfo, int, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SearchAccessors", arg0, arg1, arg2, arg3)
	ret0, _ := ret[0].([]models.AccessorInfo)
	ret1, _ := ret[1].(int)
	ret2, _ := ret[2].(error)
	return ret0, ret1, ret2
}

// SearchAccessors indicates an expected call of SearchAccessors.
func (mr *MockManagementMockRecorder) SearchAccessors(arg0, arg1, arg2, arg3 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SearchAccessors", reflect.TypeOf((*MockManagement)(nil).SearchAccessors), arg0, arg1, arg2, arg3)
}

// SearchNetwork mocks base method.
func (m *MockManagement) SearchNetwork(arg0 string, arg1, arg2 int) ([]models.WebNetworkRestriction, int, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SearchNetwork", arg0, arg1, arg2)
	ret0, _ := ret[0].([]models.WebNetworkRestriction)
	ret1, _ := ret[1].(int)
	ret2, _ := ret[2].(error)
	return ret0, ret1, ret2
}

// SearchNetwork indicates an expected call of SearchNetwork.
func (mr *MockManagementMockRecorder) SearchNetwork(arg0, arg1, arg2 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SearchNetwork", reflect.TypeOf((*MockManagement)(nil).SearchNetwork), arg0, arg1, arg2)
}

// UpdateUserDepartmentRelation mocks base method.
func (m *MockManagement) UpdateUserDepartmentRelation(userId string, departmentPaths []string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateUserDepartmentRelation", userId, departmentPaths)
	ret0, _ := ret[0].(error)
	return ret0
}

// UpdateUserDepartmentRelation indicates an expected call of UpdateUserDepartmentRelation.
func (mr *MockManagementMockRecorder) UpdateUserDepartmentRelation(userId, departmentPaths interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateUserDepartmentRelation", reflect.TypeOf((*MockManagement)(nil).UpdateUserDepartmentRelation), userId, departmentPaths)
}
