// Code generated by MockGen. DO NOT EDIT.
// Source: ./general.go
//
// Generated by this command:
//
//	mockgen -package mock_general -source ./general.go -destination test/mock_general/general_mock.go
//

// Package mock_general is a generated GoMock package.
package mock_general
