// Code generated by MockGen. DO NOT EDIT.
// Source: ./dependency.go
//
// Generated by this command:
//
//	mockgen -source=./dependency.go -package=mock_dependency --destination=../test/mock_dependency/dependency_mock.go
//

// Package mock_dependency is a generated GoMock package.
package mock_dependency

import (
	reflect "reflect"

	gomock "go.uber.org/mock/gomock"
)

// MockAbstractDriven is a mock of AbstractDriven interface.
type MockAbstractDriven struct {
	ctrl     *gomock.Controller
	recorder *MockAbstractDrivenMockRecorder
	isgomock struct{}
}

// MockAbstractDrivenMockRecorder is the mock recorder for MockAbstractDriven.
type MockAbstractDrivenMockRecorder struct {
	mock *MockAbstractDriven
}

// NewMockAbstractDriven creates a new mock instance.
func NewMockAbstractDriven(ctrl *gomock.Controller) *MockAbstractDriven {
	mock := &MockAbstractDriven{ctrl: ctrl}
	mock.recorder = &MockAbstractDrivenMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockAbstractDriven) EXPECT() *MockAbstractDrivenMockRecorder {
	return m.recorder
}

// GetBelongDepartByUserId mocks base method.
func (m *MockAbstractDriven) GetBelongDepartByUserId(userId string) ([]string, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetBelongDepartByUserId", userId)
	ret0, _ := ret[0].([]string)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetBelongDepartByUserId indicates an expected call of GetBelongDepartByUserId.
func (mr *MockAbstractDrivenMockRecorder) GetBelongDepartByUserId(userId any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetBelongDepartByUserId", reflect.TypeOf((*MockAbstractDriven)(nil).GetBelongDepartByUserId), userId)
}

// GetDepartUserIds mocks base method.
func (m *MockAbstractDriven) GetDepartUserIds(departmentId string) ([]string, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetDepartUserIds", departmentId)
	ret0, _ := ret[0].([]string)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetDepartUserIds indicates an expected call of GetDepartUserIds.
func (mr *MockAbstractDrivenMockRecorder) GetDepartUserIds(departmentId any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetDepartUserIds", reflect.TypeOf((*MockAbstractDriven)(nil).GetDepartUserIds), departmentId)
}
