// Code generated by Thrift Compiler (0.19.0). DO NOT EDIT.

package main

import (
	"context"
	"flag"
	"fmt"
	"math"
	"net"
	"net/url"
	"os"
	"strconv"
	"strings"
	thrift "github.com/kweaver-ai/go-lib/thrift"
	"Authentication/tapi/ethriftexception"
	"Authentication/tapi/evfs"
	"Authentication/tapi/eacplog"
)

var _ = ethriftexception.GoUnusedProtection__
var _ = evfs.GoUnusedProtection__
var _ = eacplog.GoUnusedProtection__

func Usage() {
  fmt.Fprintln(os.Stderr, "Usage of ", os.Args[0], " [-h host:port] [-u url] [-f[ramed]] function [arg1 [arg2...]]:")
  flag.PrintDefaults()
  fmt.Fprintln(os.Stderr, "\nFunctions:")
  fmt.Fprintln(os.Stderr, "  void Log(ncTLogItem item)")
  fmt.Fprintln(os.Stderr, "  ncTLogCountInfo GetLogCount(ncTGetLogCountParam param)")
  fmt.Fprintln(os.Stderr, "   GetPageLog(ncTGetPageLogParam param)")
  fmt.Fprintln(os.Stderr, "  string ExportLog(ncTExportLogParam param)")
  fmt.Fprintln(os.Stderr, "  void SetLogRetentionPeriod(i32 period)")
  fmt.Fprintln(os.Stderr, "  i32 GetLogRetentionPeriod()")
  fmt.Fprintln(os.Stderr, "   GetHistoryLogs(ncTLogType logType)")
  fmt.Fprintln(os.Stderr, "  i64 GetHistoryLogCount(ncTGetHistoryLogCountParam param)")
  fmt.Fprintln(os.Stderr, "   GetPageHistoryLog(ncTGetPageHistoryLogParam param)")
  fmt.Fprintln(os.Stderr, "  ncTEVFSOSSRequest GetHistoryLogDownLoadInfo(string id, string reqHost, bool useHttps, i64 validSeconds)")
  fmt.Fprintln(os.Stderr, "  string ReadHistoryLog(string fileId, i64 offset, i32 length)")
  fmt.Fprintln(os.Stderr, "  ncTLogSpaceInfo GetLogSpaceInfo()")
  fmt.Fprintln(os.Stderr, "   GetBufferedLogs()")
  fmt.Fprintln(os.Stderr, "  void SetSyslogFirstPushTime(i64 time)")
  fmt.Fprintln(os.Stderr, "  void SetLogPushPeriod(i32 period)")
  fmt.Fprintln(os.Stderr, "  i32 GetLogPushPeriod()")
  fmt.Fprintln(os.Stderr, "  void SetSecretConfig(string key, bool value)")
  fmt.Fprintln(os.Stderr, "  bool GetSecretConfig(string key)")
  fmt.Fprintln(os.Stderr)
  os.Exit(0)
}

type httpHeaders map[string]string

func (h httpHeaders) String() string {
  var m map[string]string = h
  return fmt.Sprintf("%s", m)
}

func (h httpHeaders) Set(value string) error {
  parts := strings.Split(value, ": ")
  if len(parts) != 2 {
    return fmt.Errorf("header should be of format 'Key: Value'")
  }
  h[parts[0]] = parts[1]
  return nil
}

func main() {
  flag.Usage = Usage
  var host string
  var port int
  var protocol string
  var urlString string
  var framed bool
  var useHttp bool
  headers := make(httpHeaders)
  var parsedUrl *url.URL
  var trans thrift.TTransport
  _ = strconv.Atoi
  _ = math.Abs
  flag.Usage = Usage
  flag.StringVar(&host, "h", "localhost", "Specify host and port")
  flag.IntVar(&port, "p", 9090, "Specify port")
  flag.StringVar(&protocol, "P", "binary", "Specify the protocol (binary, compact, simplejson, json)")
  flag.StringVar(&urlString, "u", "", "Specify the url")
  flag.BoolVar(&framed, "framed", false, "Use framed transport")
  flag.BoolVar(&useHttp, "http", false, "Use http")
  flag.Var(headers, "H", "Headers to set on the http(s) request (e.g. -H \"Key: Value\")")
  flag.Parse()
  
  if len(urlString) > 0 {
    var err error
    parsedUrl, err = url.Parse(urlString)
    if err != nil {
      fmt.Fprintln(os.Stderr, "Error parsing URL: ", err)
      flag.Usage()
    }
    host = parsedUrl.Host
    useHttp = len(parsedUrl.Scheme) <= 0 || parsedUrl.Scheme == "http" || parsedUrl.Scheme == "https"
  } else if useHttp {
    _, err := url.Parse(fmt.Sprint("http://", host, ":", port))
    if err != nil {
      fmt.Fprintln(os.Stderr, "Error parsing URL: ", err)
      flag.Usage()
    }
  }
  
  cmd := flag.Arg(0)
  var err error
  var cfg *thrift.TConfiguration = nil
  if useHttp {
    trans, err = thrift.NewTHttpClient(parsedUrl.String())
    if len(headers) > 0 {
      httptrans := trans.(*thrift.THttpClient)
      for key, value := range headers {
        httptrans.SetHeader(key, value)
      }
    }
  } else {
    portStr := fmt.Sprint(port)
    if strings.Contains(host, ":") {
           host, portStr, err = net.SplitHostPort(host)
           if err != nil {
                   fmt.Fprintln(os.Stderr, "error with host:", err)
                   os.Exit(1)
           }
    }
    trans = thrift.NewTSocketConf(net.JoinHostPort(host, portStr), cfg)
    if err != nil {
      fmt.Fprintln(os.Stderr, "error resolving address:", err)
      os.Exit(1)
    }
    if framed {
      trans = thrift.NewTFramedTransportConf(trans, cfg)
    }
  }
  if err != nil {
    fmt.Fprintln(os.Stderr, "Error creating transport", err)
    os.Exit(1)
  }
  defer trans.Close()
  var protocolFactory thrift.TProtocolFactory
  switch protocol {
  case "compact":
    protocolFactory = thrift.NewTCompactProtocolFactoryConf(cfg)
    break
  case "simplejson":
    protocolFactory = thrift.NewTSimpleJSONProtocolFactoryConf(cfg)
    break
  case "json":
    protocolFactory = thrift.NewTJSONProtocolFactory()
    break
  case "binary", "":
    protocolFactory = thrift.NewTBinaryProtocolFactoryConf(cfg)
    break
  default:
    fmt.Fprintln(os.Stderr, "Invalid protocol specified: ", protocol)
    Usage()
    os.Exit(1)
  }
  iprot := protocolFactory.GetProtocol(trans)
  oprot := protocolFactory.GetProtocol(trans)
  client := eacplog.NewNcTEACPLogClient(thrift.NewTStandardClient(iprot, oprot))
  if err := trans.Open(); err != nil {
    fmt.Fprintln(os.Stderr, "Error opening socket to ", host, ":", port, " ", err)
    os.Exit(1)
  }
  
  switch cmd {
  case "Log":
    if flag.NArg() - 1 != 1 {
      fmt.Fprintln(os.Stderr, "Log requires 1 args")
      flag.Usage()
    }
    arg141 := flag.Arg(1)
    mbTrans142 := thrift.NewTMemoryBufferLen(len(arg141))
    defer mbTrans142.Close()
    _, err143 := mbTrans142.WriteString(arg141)
    if err143 != nil {
      Usage()
      return
    }
    factory144 := thrift.NewTJSONProtocolFactory()
    jsProt145 := factory144.GetProtocol(mbTrans142)
    argvalue0 := eacplog.NewNcTLogItem()
    err146 := argvalue0.Read(context.Background(), jsProt145)
    if err146 != nil {
      Usage()
      return
    }
    value0 := argvalue0
    fmt.Print(client.Log(context.Background(), value0))
    fmt.Print("\n")
    break
  case "GetLogCount":
    if flag.NArg() - 1 != 1 {
      fmt.Fprintln(os.Stderr, "GetLogCount requires 1 args")
      flag.Usage()
    }
    arg147 := flag.Arg(1)
    mbTrans148 := thrift.NewTMemoryBufferLen(len(arg147))
    defer mbTrans148.Close()
    _, err149 := mbTrans148.WriteString(arg147)
    if err149 != nil {
      Usage()
      return
    }
    factory150 := thrift.NewTJSONProtocolFactory()
    jsProt151 := factory150.GetProtocol(mbTrans148)
    argvalue0 := eacplog.NewNcTGetLogCountParam()
    err152 := argvalue0.Read(context.Background(), jsProt151)
    if err152 != nil {
      Usage()
      return
    }
    value0 := argvalue0
    fmt.Print(client.GetLogCount(context.Background(), value0))
    fmt.Print("\n")
    break
  case "GetPageLog":
    if flag.NArg() - 1 != 1 {
      fmt.Fprintln(os.Stderr, "GetPageLog requires 1 args")
      flag.Usage()
    }
    arg153 := flag.Arg(1)
    mbTrans154 := thrift.NewTMemoryBufferLen(len(arg153))
    defer mbTrans154.Close()
    _, err155 := mbTrans154.WriteString(arg153)
    if err155 != nil {
      Usage()
      return
    }
    factory156 := thrift.NewTJSONProtocolFactory()
    jsProt157 := factory156.GetProtocol(mbTrans154)
    argvalue0 := eacplog.NewNcTGetPageLogParam()
    err158 := argvalue0.Read(context.Background(), jsProt157)
    if err158 != nil {
      Usage()
      return
    }
    value0 := argvalue0
    fmt.Print(client.GetPageLog(context.Background(), value0))
    fmt.Print("\n")
    break
  case "ExportLog":
    if flag.NArg() - 1 != 1 {
      fmt.Fprintln(os.Stderr, "ExportLog requires 1 args")
      flag.Usage()
    }
    arg159 := flag.Arg(1)
    mbTrans160 := thrift.NewTMemoryBufferLen(len(arg159))
    defer mbTrans160.Close()
    _, err161 := mbTrans160.WriteString(arg159)
    if err161 != nil {
      Usage()
      return
    }
    factory162 := thrift.NewTJSONProtocolFactory()
    jsProt163 := factory162.GetProtocol(mbTrans160)
    argvalue0 := eacplog.NewNcTExportLogParam()
    err164 := argvalue0.Read(context.Background(), jsProt163)
    if err164 != nil {
      Usage()
      return
    }
    value0 := argvalue0
    fmt.Print(client.ExportLog(context.Background(), value0))
    fmt.Print("\n")
    break
  case "SetLogRetentionPeriod":
    if flag.NArg() - 1 != 1 {
      fmt.Fprintln(os.Stderr, "SetLogRetentionPeriod requires 1 args")
      flag.Usage()
    }
    tmp0, err165 := (strconv.Atoi(flag.Arg(1)))
    if err165 != nil {
      Usage()
      return
    }
    argvalue0 := int32(tmp0)
    value0 := argvalue0
    fmt.Print(client.SetLogRetentionPeriod(context.Background(), value0))
    fmt.Print("\n")
    break
  case "GetLogRetentionPeriod":
    if flag.NArg() - 1 != 0 {
      fmt.Fprintln(os.Stderr, "GetLogRetentionPeriod requires 0 args")
      flag.Usage()
    }
    fmt.Print(client.GetLogRetentionPeriod(context.Background()))
    fmt.Print("\n")
    break
  case "GetHistoryLogs":
    if flag.NArg() - 1 != 1 {
      fmt.Fprintln(os.Stderr, "GetHistoryLogs requires 1 args")
      flag.Usage()
    }
    tmp0, err := (strconv.Atoi(flag.Arg(1)))
    if err != nil {
      Usage()
     return
    }
    argvalue0 := eacplog.NcTLogType(tmp0)
    value0 := argvalue0
    fmt.Print(client.GetHistoryLogs(context.Background(), value0))
    fmt.Print("\n")
    break
  case "GetHistoryLogCount":
    if flag.NArg() - 1 != 1 {
      fmt.Fprintln(os.Stderr, "GetHistoryLogCount requires 1 args")
      flag.Usage()
    }
    arg166 := flag.Arg(1)
    mbTrans167 := thrift.NewTMemoryBufferLen(len(arg166))
    defer mbTrans167.Close()
    _, err168 := mbTrans167.WriteString(arg166)
    if err168 != nil {
      Usage()
      return
    }
    factory169 := thrift.NewTJSONProtocolFactory()
    jsProt170 := factory169.GetProtocol(mbTrans167)
    argvalue0 := eacplog.NewNcTGetHistoryLogCountParam()
    err171 := argvalue0.Read(context.Background(), jsProt170)
    if err171 != nil {
      Usage()
      return
    }
    value0 := argvalue0
    fmt.Print(client.GetHistoryLogCount(context.Background(), value0))
    fmt.Print("\n")
    break
  case "GetPageHistoryLog":
    if flag.NArg() - 1 != 1 {
      fmt.Fprintln(os.Stderr, "GetPageHistoryLog requires 1 args")
      flag.Usage()
    }
    arg172 := flag.Arg(1)
    mbTrans173 := thrift.NewTMemoryBufferLen(len(arg172))
    defer mbTrans173.Close()
    _, err174 := mbTrans173.WriteString(arg172)
    if err174 != nil {
      Usage()
      return
    }
    factory175 := thrift.NewTJSONProtocolFactory()
    jsProt176 := factory175.GetProtocol(mbTrans173)
    argvalue0 := eacplog.NewNcTGetPageHistoryLogParam()
    err177 := argvalue0.Read(context.Background(), jsProt176)
    if err177 != nil {
      Usage()
      return
    }
    value0 := argvalue0
    fmt.Print(client.GetPageHistoryLog(context.Background(), value0))
    fmt.Print("\n")
    break
  case "GetHistoryLogDownLoadInfo":
    if flag.NArg() - 1 != 4 {
      fmt.Fprintln(os.Stderr, "GetHistoryLogDownLoadInfo requires 4 args")
      flag.Usage()
    }
    argvalue0 := flag.Arg(1)
    value0 := argvalue0
    argvalue1 := flag.Arg(2)
    value1 := argvalue1
    argvalue2 := flag.Arg(3) == "true"
    value2 := argvalue2
    argvalue3, err181 := (strconv.ParseInt(flag.Arg(4), 10, 64))
    if err181 != nil {
      Usage()
      return
    }
    value3 := argvalue3
    fmt.Print(client.GetHistoryLogDownLoadInfo(context.Background(), value0, value1, value2, value3))
    fmt.Print("\n")
    break
  case "ReadHistoryLog":
    if flag.NArg() - 1 != 3 {
      fmt.Fprintln(os.Stderr, "ReadHistoryLog requires 3 args")
      flag.Usage()
    }
    argvalue0 := flag.Arg(1)
    value0 := argvalue0
    argvalue1, err183 := (strconv.ParseInt(flag.Arg(2), 10, 64))
    if err183 != nil {
      Usage()
      return
    }
    value1 := argvalue1
    tmp2, err184 := (strconv.Atoi(flag.Arg(3)))
    if err184 != nil {
      Usage()
      return
    }
    argvalue2 := int32(tmp2)
    value2 := argvalue2
    fmt.Print(client.ReadHistoryLog(context.Background(), value0, value1, value2))
    fmt.Print("\n")
    break
  case "GetLogSpaceInfo":
    if flag.NArg() - 1 != 0 {
      fmt.Fprintln(os.Stderr, "GetLogSpaceInfo requires 0 args")
      flag.Usage()
    }
    fmt.Print(client.GetLogSpaceInfo(context.Background()))
    fmt.Print("\n")
    break
  case "GetBufferedLogs":
    if flag.NArg() - 1 != 0 {
      fmt.Fprintln(os.Stderr, "GetBufferedLogs requires 0 args")
      flag.Usage()
    }
    fmt.Print(client.GetBufferedLogs(context.Background()))
    fmt.Print("\n")
    break
  case "SetSyslogFirstPushTime":
    if flag.NArg() - 1 != 1 {
      fmt.Fprintln(os.Stderr, "SetSyslogFirstPushTime requires 1 args")
      flag.Usage()
    }
    argvalue0, err185 := (strconv.ParseInt(flag.Arg(1), 10, 64))
    if err185 != nil {
      Usage()
      return
    }
    value0 := argvalue0
    fmt.Print(client.SetSyslogFirstPushTime(context.Background(), value0))
    fmt.Print("\n")
    break
  case "SetLogPushPeriod":
    if flag.NArg() - 1 != 1 {
      fmt.Fprintln(os.Stderr, "SetLogPushPeriod requires 1 args")
      flag.Usage()
    }
    tmp0, err186 := (strconv.Atoi(flag.Arg(1)))
    if err186 != nil {
      Usage()
      return
    }
    argvalue0 := int32(tmp0)
    value0 := argvalue0
    fmt.Print(client.SetLogPushPeriod(context.Background(), value0))
    fmt.Print("\n")
    break
  case "GetLogPushPeriod":
    if flag.NArg() - 1 != 0 {
      fmt.Fprintln(os.Stderr, "GetLogPushPeriod requires 0 args")
      flag.Usage()
    }
    fmt.Print(client.GetLogPushPeriod(context.Background()))
    fmt.Print("\n")
    break
  case "SetSecretConfig":
    if flag.NArg() - 1 != 2 {
      fmt.Fprintln(os.Stderr, "SetSecretConfig requires 2 args")
      flag.Usage()
    }
    argvalue0 := flag.Arg(1)
    value0 := argvalue0
    argvalue1 := flag.Arg(2) == "true"
    value1 := argvalue1
    fmt.Print(client.SetSecretConfig(context.Background(), value0, value1))
    fmt.Print("\n")
    break
  case "GetSecretConfig":
    if flag.NArg() - 1 != 1 {
      fmt.Fprintln(os.Stderr, "GetSecretConfig requires 1 args")
      flag.Usage()
    }
    argvalue0 := flag.Arg(1)
    value0 := argvalue0
    fmt.Print(client.GetSecretConfig(context.Background(), value0))
    fmt.Print("\n")
    break
  case "":
    Usage()
    break
  default:
    fmt.Fprintln(os.Stderr, "Invalid function ", cmd)
  }
}
