// Code generated by MockGen. DO NOT EDIT.
// Source: policy_mgnt/general (interfaces: Management)

// Package mock_general is a generated GoMock package.
package mock_general

import (
	reflect "reflect"

	general "policy_mgnt/general"
	models "policy_mgnt/utils/models"

	gomock "go.uber.org/mock/gomock"
)

// MockManagement is a mock of Management interface
type MockManagement struct {
	ctrl     *gomock.Controller
	recorder *MockManagementMockRecorder
}

// MockManagementMockRecorder is the mock recorder for MockManagement
type MockManagementMockRecorder struct {
	mock *MockManagement
}

// NewMockManagement creates a new mock instance
func NewMockManagement(ctrl *gomock.Controller) *MockManagement {
	mock := &MockManagement{ctrl: ctrl}
	mock.recorder = &MockManagementMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use
func (m *MockManagement) EXPECT() *MockManagementMockRecorder {
	return m.recorder
}

// ListPolicy mocks base method
func (m *MockManagement) ListPolicy(arg0, arg1 int, arg2 []string) ([]models.Policy[[]byte], int, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListPolicy", arg0, arg1, arg2)
	ret0, _ := ret[0].([]models.Policy[[]byte])
	ret1, _ := ret[1].(int)
	ret2, _ := ret[2].(error)
	return ret0, ret1, ret2
}

// ListPolicy indicates an expected call of ListPolicy
func (mr *MockManagementMockRecorder) ListPolicy(arg0, arg1, arg2 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListPolicy", reflect.TypeOf((*MockManagement)(nil).ListPolicy), arg0, arg1, arg2)
}

// SetPolicyState mocks base method
func (m *MockManagement) SetPolicyState(arg0 []string, arg1 map[general.State]interface{}) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SetPolicyState", arg0, arg1)
	ret0, _ := ret[0].(error)
	return ret0
}

// SetPolicyState indicates an expected call of SetPolicyState
func (mr *MockManagementMockRecorder) SetPolicyState(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SetPolicyState", reflect.TypeOf((*MockManagement)(nil).SetPolicyState), arg0, arg1)
}

// SetPolicyValue mocks base method
func (m *MockManagement) SetPolicyValue(arg0 map[string][]byte, arg1 bool) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SetPolicyValue", arg0, arg1)
	ret0, _ := ret[0].(error)
	return ret0
}

// SetPolicyValue indicates an expected call of SetPolicyValue
func (mr *MockManagementMockRecorder) SetPolicyValue(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SetPolicyValue", reflect.TypeOf((*MockManagement)(nil).SetPolicyValue), arg0, arg1)
}
