// Code generated by MockGen. DO NOT EDIT.
// Source: policy_mgnt/general (interfaces: PolicyValue)

// Package mock_general is a generated GoMock package.
package mock_general

import (
	reflect "reflect"

	gomock "go.uber.org/mock/gomock"
)

// MockPolicyValue is a mock of PolicyValue interface
type MockPolicyValue struct {
	ctrl     *gomock.Controller
	recorder *MockPolicyValueMockRecorder
}

// MockPolicyValueMockRecorder is the mock recorder for MockPolicyValue
type MockPolicyValueMockRecorder struct {
	mock *MockPolicyValue
}

// NewMockPolicyValue creates a new mock instance
func NewMockPolicyValue(ctrl *gomock.Controller) *MockPolicyValue {
	mock := &MockPolicyValue{ctrl: ctrl}
	mock.recorder = &MockPolicyValueMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use
func (m *MockPolicyValue) EXPECT() *MockPolicyValueMockRecorder {
	return m.recorder
}

// CheckParams mocks base method
func (m *MockPolicyValue) CheckParams() error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CheckParams")
	ret0, _ := ret[0].(error)
	return ret0
}

// CheckParams indicates an expected call of CheckParams
func (mr *MockPolicyValueMockRecorder) CheckParams() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CheckParams", reflect.TypeOf((*MockPolicyValue)(nil).CheckParams))
}

// Merge mocks base method
func (m *MockPolicyValue) Merge(arg0 []byte) ([]byte, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Merge", arg0)
	ret0, _ := ret[0].([]byte)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Merge indicates an expected call of Merge
func (mr *MockPolicyValueMockRecorder) Merge(arg0 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Merge", reflect.TypeOf((*MockPolicyValue)(nil).Merge), arg0)
}

// Name mocks base method
func (m *MockPolicyValue) Name() string {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Name")
	ret0, _ := ret[0].(string)
	return ret0
}

// Name indicates an expected call of Name
func (mr *MockPolicyValueMockRecorder) Name() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Name", reflect.TypeOf((*MockPolicyValue)(nil).Name))
}
