// Code generated by MockGen. DO NOT EDIT.
// Source: ./redis_conn.go

// Package mock_logics is a generated GoMock package.
package mock_logics

import (
	reflect "reflect"

	gomock "go.uber.org/mock/gomock"
)

// MockRedisConn is a mock of RedisConn interface.
type MockRedisConn struct {
	ctrl     *gomock.Controller
	recorder *MockRedisConnMockRecorder
}

// MockRedisConnMockRecorder is the mock recorder for MockRedisConn.
type MockRedisConnMockRecorder struct {
	mock *MockRedisConn
}

// NewMockRedisConn creates a new mock instance.
func NewMockRedisConn(ctrl *gomock.Controller) *MockRedisConn {
	mock := &MockRedisConn{ctrl: ctrl}
	mock.recorder = &MockRedisConnMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockRedisConn) EXPECT() *MockRedisConnMockRecorder {
	return m.recorder
}

// Publish mocks base method.
func (m *MockRedisConn) Publish(channel string, message []byte) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Publish", channel, message)
	ret0, _ := ret[0].(error)
	return ret0
}

// Publish indicates an expected call of Publish.
func (mr *MockRedisConnMockRecorder) Publish(channel, message interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Publish", reflect.TypeOf((*MockRedisConn)(nil).Publish), channel, message)
}

// Subscribe mocks base method.
func (m *MockRedisConn) Subscribe(channel string, cmd func([]byte)) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Subscribe", channel, cmd)
	ret0, _ := ret[0].(error)
	return ret0
}

// Subscribe indicates an expected call of Subscribe.
func (mr *MockRedisConnMockRecorder) Subscribe(channel, cmd interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Subscribe", reflect.TypeOf((*MockRedisConn)(nil).Subscribe), channel, cmd)
}
