// Code generated by MockGen. DO NOT EDIT.
// Source: ../utils/acl.go

// Package mock is a generated GoMock package.
package mock_acl

import (
	reflect "reflect"

	gomock "go.uber.org/mock/gomock"
)

// MockACLClient is a mock of ACLClient interface
type MockACLClient struct {
	ctrl     *gomock.Controller
	recorder *MockACLClientMockRecorder
}

// MockACLClientMockRecorder is the mock recorder for MockACLClient
type MockACLClientMockRecorder struct {
	mock *MockACLClient
}

// NewMockACLClient creates a new mock instance
func NewMockACLClient(ctrl *gomock.Controller) *MockACLClient {
	mock := &MockACLClient{ctrl: ctrl}
	mock.recorder = &MockACLClientMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use
func (m *MockACLClient) EXPECT() *MockACLClientMockRecorder {
	return m.recorder
}

// Pass mocks base method
func (m *MockACLClient) Pass(clientID string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Pass", clientID)
	ret0, _ := ret[0].(error)
	return ret0
}

// Pass indicates an expected call of Pass
func (mr *MockACLClientMockRecorder) Pass(clientID interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Pass", reflect.TypeOf((*MockACLClient)(nil).Pass), clientID)
}
