// Code generated by Thrift Compiler (0.19.0). DO NOT EDIT.

package evfs

import (
	"bytes"
	"context"
	"errors"
	"fmt"
	"time"
	thrift "github.com/kweaver-ai/go-lib/thrift"
	"strings"
	"regexp"
	"Authentication/tapi/ethriftexception"

)

// (needed to ensure safety because of naive import list construction.)
var _ = thrift.ZERO
var _ = fmt.Printf
var _ = errors.New
var _ = context.Background
var _ = time.Now
var _ = bytes.Equal
// (needed by validator.)
var _ = strings.Contains
var _ = regexp.MatchString

var _ = ethriftexception.GoUnusedProtection__
const NCT_EVFS_PORT = 9064
const NCT_EVFS_ERR_PROVIDER_NAME = "evfstimpl"

func init() {
}

